'use strict';
// Tests for the NEW reference modules in this MD only. Not an Electron/Windows/live-Agent claim.
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const load=n=>require('../app/production-v2/'+n);
const C=load('contracts'),D=load('domain'),A=load('approval-policy'),S=load('shot-commands'),AS=load('asset-commands'),V=load('video-snapshot'),P=load('post-plan'),G=load('prompt-edit-guard'),T=load('text-completeness');
const {ProductionRepository}=load('repository'),{PromptChatService}=load('prompt-chat');
const actor={id:'local-user',type:'user'},at='2026-09-18T00:00:00.000Z',ctx={at,actor,validatedCandidateIds:new Set()};
function prompt(){return {id:'i',entityId:'s',entityType:'shot',stage:'shot_video',itemRevision:1,displayPrompt:'原稿甲',prompt:'Original',providerContractId:'fixture-model-v1',logicalReferences:[],dialogueIds:[],sourceFactHash:'source-facts',policyHash:'policy'};}
function project(id='p'){const i=prompt();i.validation={version:'prompt-content-r2',contentHash:D.itemHash(i),schemaValid:true,coverageComplete:true,verdict:'pass'};return {id,productionV2:{enabled:true,epoch:'E',sourceRevision:'S',textComplete:true,phase:'review_ready',reviewGate:{epoch:'E',status:'ready'},options:{continueToPost:true},postPolicy:{audioMode:'none'}},shots:[{id:'s',number:1,characterIds:[],dialogueTurns:[],submissionInputHash:'INPUT'}],characters:[],candidates:[],promptReview:{items:[i]}};}
function fixture(projects=[project()]){
 const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE project_state(project_id TEXT PRIMARY KEY,revision INTEGER,snapshot_json TEXT);CREATE TABLE operation_outbox(operation_key TEXT UNIQUE,operation_id TEXT PRIMARY KEY,project_id TEXT,kind TEXT,target_id TEXT,input_fingerprint TEXT,contract_fingerprint TEXT,payload_json TEXT,status TEXT,attempts INTEGER,created_at TEXT,updated_at TEXT,error_kind TEXT,error_code TEXT,result_json TEXT);CREATE TABLE test_meta(k TEXT PRIMARY KEY,v TEXT);CREATE TABLE test_events(event_id TEXT,type TEXT);`);
 for(const p of projects)db.prepare('INSERT INTO project_state VALUES(?,1,?)').run(p.id,JSON.stringify(p));
 let clock=at;const store={db,transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();if(r?.then)throw Error('async transaction');db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}},setMeta(k,v){db.prepare('INSERT INTO test_meta VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,JSON.stringify(v));},projectRow(id){return db.prepare('SELECT * FROM project_state WHERE project_id=?').get(id);},commitProjectInTransaction(p){const r=this.projectRow(p.id).revision+1;db.prepare('UPDATE project_state SET revision=?,snapshot_json=? WHERE project_id=?').run(r,JSON.stringify(p),p.id);return {revision:r};},appendEvent(e){db.prepare('INSERT INTO test_events VALUES(?,?)').run(e.eventId,e.type);}};
 load('migrate-r2').migrate(store);
 const repo=new ProductionRepository(store,{now:()=>clock,authorize(a,id){if(a?.id!==actor.id||!store.projectRow(id))throw C.fail('UNAUTHORIZED','Denied');},validateCommit:()=>({valid:true,current:true})}); // Trusted validator stub ONLY in this repository-state fixture.
 return {db,store,repo,now:n=>clock=n,close:()=>db.close(),get:id=>JSON.parse(store.projectRow(id||'p').snapshot_json)};
}
function cmd(f,extra={}){return f.repo.commitCommand({projectId:'p',commandId:'c',commandType:'name',expectedRevision:1,actor,payload:{name:'new'},mutate:p=>({project:{...p,name:'new'},result:{projectId:p.id}}),...extra});}
function queue(f,effectClass='local'){return f.store.transaction(()=>{const body={projectId:'p',source:'S'},h=f.repo.saveInputInTransaction('p','fixture',body);return f.repo.enqueueOperationInTransaction({projectId:'p',kind:'fixture',inputFingerprint:h,effectClass});});}
function ready(){const p=project();p.candidates=[{id:'v',entityType:'shot',entityId:'s',stage:'shot_video',selected:true,inputFingerprint:'INPUT',filePath:'/managed/v.mp4'}];const evidence=new Map([['v',{id:'proof',projectId:'p',candidateId:'v',validationVersion:'media-local-r2',mediaHash:'mediahash',filePath:'/managed/v.mp4',hasVideo:true,hasAudio:true,decodable:true,state:'valid',durationUs:2000000}]]);return {p,evidence};}
const catches=(fn,code)=>assert.throws(fn,e=>e.code===code || e.code?.startsWith(code));
test('C01 stable UUID: same asset name does not collide',()=>{const p=project();AS.handleAssetCommand(p,'asset.create',{kind:'character',name:'同名'},ctx);AS.handleAssetCommand(p,'asset.create',{kind:'character',name:'同名'},ctx);assert.notEqual(p.characters[0].id,p.characters[1].id);});
test('C02 unsupported asset kind rejected',()=>catches(()=>AS.handleAssetCommand(project(),'asset.create',{kind:'xxx',name:'x'},ctx),'ASSET_KIND_INVALID'));
test('C03 a1 is not a10 and actual reference fields are read',()=>{const p=project();p.shots[0].characterIds=['a10'];assert.deepEqual(D.referencesOf(p,'a1'),[]);assert.deepEqual(D.referencesOf(p,'a10'),['s']);});
test('C04 clone does not copy real dialogue or execution',()=>{const p=project();Object.assign(p.shots[0],{dialogueTurns:[{text:'原句'}],shotExecution:{dialogue:['原句']},manualVideoPrompt:'原句'});S.handleShotCommand(p,'shot.clone',{shotId:'s'},ctx);assert.deepEqual(p.shots[1].dialogueTurns,[]);assert.equal(p.shots[1].manualVideoPrompt,undefined);assert.equal(p.shots[1].shotExecution,undefined);});
test('C05 reorder projects legacy number into same order',()=>{const p=project();p.shots.push({id:'s2',number:2});S.handleShotCommand(p,'shot.reorder',{orderedShotIds:['s2','s']},ctx);assert.deepEqual([...p.shots].sort((a,b)=>a.number-b.number).map(x=>x.id),['s2','s']);});
test('C06 missing candidate always rejected',()=>catches(()=>S.handleShotCommand(project(),'shot.chooseVideo',{shotId:'s',candidateId:'none'},ctx),'VIDEO_CANDIDATE_NOT_READY'));
test('C07 explicit selected candidate required, no implicit first',()=>{const {p,evidence}=ready();p.candidates[0].selected=false;assert.equal(V.resolveSelectedVideos(p,evidence).ready,false);});
test('C08 verified flag is not physical evidence',()=>{const {p}=ready();p.candidates[0].verified=true;assert.equal(V.resolveSelectedVideos(p,new Map()).ready,false);});
test('C09 no shots is not all complete',()=>assert.equal(V.resolveSelectedVideos(project(),new Map()).ready,false));
test('C10 validated selected existing-format candidate works without verified flag',()=>{const {p,evidence}=ready();assert.equal(V.resolveSelectedVideos(p,evidence).ready,true);});
test('C11 old video is not silently current',()=>{const {p,evidence}=ready();p.candidates[0].stale=true;assert.equal(V.resolveSelectedVideos(p,evidence).ready,false);});
test('C12 snapshot changes for changed selected media',()=>{const {p,evidence}=ready();const a=V.snapshot(p,V.resolveSelectedVideos(p,evidence),{}).hash;evidence.get('v').mediaHash='different';const b=V.snapshot(p,V.resolveSelectedVideos(p,evidence),{}).hash;assert.notEqual(a,b);});
test('C13 snapshot includes project identity',()=>{const a=ready(),b=ready();b.p.id='other';b.evidence.get('v').projectId='other';assert.notEqual(V.snapshot(a.p,V.resolveSelectedVideos(a.p,a.evidence),{}).hash,V.snapshot(b.p,V.resolveSelectedVideos(b.p,b.evidence),{}).hash);});
test('C14 explicit false wins auto policy',()=>{const p=project();p.productionV2.options.continueToPost=false;assert.equal(V.shouldAutoPost(p),false);});
test('C15 initial popup consumed at most once',()=>{let v=project().productionV2;const r=A.acknowledgeAutoOpen(v,'E',at);assert.equal(r.consumed,true);assert.equal(A.acknowledgeAutoOpen(r.state,'E',at).consumed,false);});
test('C16 popup never opens after production starts',()=>{const v=project().productionV2;v.productionStartedAt=at;assert.equal(A.mayAutoOpen(v),false);});
test('C17 cannot approve caller-invented item',()=>catches(()=>A.approve(project(),[{id:'fake',expectedContentHash:'h'}],{actor,at,validatorVersion:'prompt-content-r2'}),'PROMPT_NOT_FOUND'));
test('C18 approval covers every requested item, including absent ones',()=>{const p=project(),a=A.approve(p,[{id:'i',expectedContentHash:D.itemHash(p.promptReview.items[0])}],{actor,at,validatorVersion:'prompt-content-r2'});catches(()=>A.assertApproved(p,['i','missing'],[a],'prompt-content-r2'),'PROMPT_NOT_FOUND');});
test('C19 changed content invalidates original approval',()=>{const p=project(),a=A.approve(p,[{id:'i',expectedContentHash:D.itemHash(p.promptReview.items[0])}],{actor,at,validatorVersion:'prompt-content-r2'});p.promptReview.items[0].prompt='changed';catches(()=>A.assertApproved(p,['i'],[a],'prompt-content-r2'),'PROMPT_NOT_READY');});
test('C20 whole-item edit uses stored base, not caller updated version',()=>{const i=prompt(),base=G.prepareBase(i),proposal={displayPrompt:'改稿',executionPrompt:'new'};const t={status:'proposal_ready',base,proposal,validation:{valid:true,baseContentHash:base.baseContentHash,proposalHash:C.hash(proposal)}};i.itemRevision=2;catches(()=>G.assertApplicable(i,t),'EDIT_CONFLICT');});
test('C21 cancelled proposal cannot apply',()=>{const i=prompt();catches(()=>G.assertApplicable(i,{status:'cancelled'}),'PROPOSAL_NOT_APPLICABLE');});
test('C22 range does not split surrogate pair',()=>catches(()=>G.capture('甲😀乙',2,3),'SELECTION_SPLITS_SURROGATE'));
test('C23 selection preserves display outside range',()=>{const i=prompt(),sel=G.capture(i.displayPrompt,1,2),b=G.prepareBase(i,sel);const p=G.buildProposal(b,{verdict:'proposal',replacementDisplay:'新',proposedExecutionPrompt:'new'});assert.equal(p.displayPrompt,'原新甲');});
test('C24 application syncs actual execution and clears validation without approving',()=>{const p=project(),i=p.promptReview.items[0];D.applyPromptEdit(p,{itemId:'i',baseRevision:1,baseHash:D.itemHash(i),displayPrompt:'中文新稿',executionPrompt:'NEW_EXEC',at});assert.equal(p.shots[0].manualVideoPrompt,'NEW_EXEC');assert.equal(i.prompt,'NEW_EXEC');assert.equal(i.userConfirmed,false);assert.equal(i.validation,null);});
test('C25 successful original command replay before revision check',()=>{const f=fixture();const a=cmd(f),b=cmd(f);assert.equal(b.replayed,true);assert.equal(b.projectRevision,a.projectRevision);f.close();});
test('C26 command IDs are isolated across projects',()=>{const f=fixture([project('p'),project('q')]);cmd(f);const r=cmd(f,{projectId:'q'});assert.equal(r.result.projectId,'q');f.close();});
test('C27 same key different payload rejected',()=>{const f=fixture();cmd(f);catches(()=>cmd(f,{payload:{name:'other'}}),'IDEMPOTENCY_KEY_REUSED');f.close();});
test('C28 queued epoch0 cannot submit',()=>{const f=fixture(),op=queue(f);catches(()=>f.repo.commitOperation({operationId:op.operationId,workerId:'w',leaseEpoch:0,inputHash:'x',validationId:'v',result:{}}),'INVALID_OPERATION_LEASE');f.close();});
test('C29 completed result immutable but identical replay allowed',()=>{const f=fixture(),op=queue(f),l=f.repo.claimOperation({operationId:op.operationId,workerId:'w'}),arg={operationId:op.operationId,workerId:'w',leaseEpoch:l.leaseEpoch,inputHash:l.inputHash,validationId:'v',result:{x:1}};f.repo.commitOperation(arg);assert.equal(f.repo.commitOperation(arg).replayed,true);catches(()=>f.repo.commitOperation({...arg,result:{x:2}}),'COMPLETED_RESULT_IMMUTABLE');f.close();});
test('C30 paused operation not automatically claimable',()=>{const f=fixture(),op=queue(f);f.db.exec("UPDATE operation_outbox SET status='paused'");assert.equal(f.repo.claimOperation({operationId:op.operationId,workerId:'w'}).leased,false);f.close();});
test('C31 expired external operation reconciles not retransmits',()=>{const f=fixture(),op=queue(f,'external');f.repo.claimOperation({operationId:op.operationId,workerId:'w',leaseTtlMs:1000});f.now('2026-09-18T00:00:02.000Z');f.repo.recoverExpired();assert.equal(f.db.prepare('SELECT status FROM operation_outbox').get().status,'outcome_unknown');f.close();});
test('C32 every local retry claim increments attempts',()=>{const f=fixture(),op=queue(f);f.repo.claimOperation({operationId:op.operationId,workerId:'w',leaseTtlMs:1000});f.now('2026-09-18T00:00:02.000Z');f.repo.recoverExpired();f.repo.claimOperation({operationId:op.operationId,workerId:'w2'});assert.equal(f.db.prepare('SELECT attempts FROM operation_outbox').get().attempts,2);f.close();});
test('C33 wrong lease owner rejected',()=>{const f=fixture(),op=queue(f),l=f.repo.claimOperation({operationId:op.operationId,workerId:'w'});catches(()=>f.repo.commitOperation({operationId:op.operationId,workerId:'other',leaseEpoch:l.leaseEpoch,inputHash:l.inputHash,validationId:'v',result:{}}),'INVALID_OPERATION_LEASE');f.close();});
test('C34 migration is repeatable',()=>{const f=fixture();load('migrate-r2').migrate(f.store);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM test_meta').get().n,1);f.close();});
test('C35 command enqueues within single transaction',()=>{const f=fixture();const body={projectId:'p',type:'fixture'};const r=cmd(f,{mutate:p=>({project:p,inputs:[{kind:'fixture',body}],operations:[{kind:'fixture',effectClass:'local',inputFingerprint:C.hash(body)}]})});assert.equal(r.operations.length,1);f.close();});
test('C36 all writes rollback on finalize failure',()=>{const f=fixture();assert.throws(()=>cmd(f,{mutate:p=>({project:{...p,name:'bad'},finalizeInTransaction:()=>{throw Error('inject');}})}));assert.equal(f.store.projectRow('p').revision,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM command_log').get().n,0);f.close();});
test('C37 full source ledger is mandatory',()=>catches(()=>T.verify({project:project(),ledger:null,requiredItemIds:['i']}),'SOURCE_LEDGER_REQUIRED'));
test('C38 zero and negative batch sizes rejected',()=>{for(const n of [0,-1,1.5])catches(()=>T.createBatches([1,2],n),'BATCH_SIZE_INVALID');});
test('C39 actual user template sent',()=>{const r=load('prompt-compose').compose({stage:'x',roleId:'P08',baseBoundary:'BOUND',roleBody:'ROLE',policyVersion:'r2',userTemplate:'用户唯一要求',task:{}});assert(r.messages[1].content.includes('用户唯一要求'));assert.equal(r.provenance.userTemplateActuallySent,true);});
test('C40 same rule ID with changed text is a conflict',()=>catches(()=>load('prompt-compose').compose({stage:'x',roleId:'P08',baseBoundary:'B',roleBody:'R',policyVersion:'r2',task:{},rules:[{id:'a',body:'1'},{id:'a',body:'2'}]}),'PROMPT_RULE_CONFLICT'));
test('C41 unknown model never defaults to H3',()=>catches(()=>load('provider-contracts').compile({providerId:'x',modelId:'y',contractId:'z'},new Map()),'PROVIDER_CONTRACT_UNAVAILABLE'));
test('C42 module terminal intermediate message is not task completion',()=>assert.equal(load('terminal-policy').normalizedTerminal({eventKind:'item_completed',nativeStatus:'completed'}).terminal,false));
test('C43 max_tokens is incomplete despite text',()=>assert.equal(load('terminal-policy').normalizedTerminal({eventKind:'turn_terminal',nativeStatus:'completed',naturalEnd:true,finishReason:'max_tokens'}).status,'incomplete'));
test('C44 valid terminal without full receipt cannot complete business',()=>catches(()=>load('terminal-policy').acceptBusinessCompletion({terminal:{status:'generation_complete'}}),'DELIVERY_INCOMPLETE'));
test('C45 trim timeline uses exact retained duration',()=>{const r=P.timeline([{shotId:'s',durationUs:2000000,sourceStartUs:1000000,sourceEndUs:2000000,trimEvidenceHash:'proof'}]);assert.equal(r.totalDurationUs,1000000);});
test('C46 one invalid SFX does not discard valid cue',()=>{const plan=P.timeline([{shotId:'s',durationUs:2000000}]),effects=new Map([['fx',{verified:true,mediaHash:'h',durationUs:2000000,filePath:'x'}]]);const common={effectId:'fx',shotId:'s',timeBasis:'post_trim',durationUs:100000};const r=P.alignSfx(plan,[{...common,id:'a',offsetUs:0},{...common,id:'b',offsetUs:3000000}],effects);assert.equal(r.accepted.length,1);assert.equal(r.rejected.length,1);assert.equal(r.status,'partial_audio');});
test('C47 no-audio base is synthesized and 0 gain/time preserved',()=>{const r=load('audio-render-plan').buildAudioRender({cleanPath:'v',hasAudio:false,totalUs:2000000,cues:[{id:'q',filePath:'fx',timelineStartUs:0,durationUs:100000,gainDb:0,fadeInUs:0,fadeOutUs:0}],outputPath:'o'});assert(r.filterGraph.includes('anullsrc'));assert(r.filterGraph.includes('duration=0.100000'));assert(r.filterGraph.includes('volume=0dB'));assert(r.filterGraph.includes('adelay=0S'));});
test('C48 budget persists across object recreation',()=>{const f=fixture();let b=new (load('budget').PersistentBudget)(f.store);b.ensureRun({runId:'r',projectId:'p',sourceHash:'h'});b.reserve({runId:'r',unitId:'u',attemptId:'1'});b=new (load('budget').PersistentBudget)(f.store);b.reserve({runId:'r',unitId:'u',attemptId:'2'});catches(()=>b.reserve({runId:'r',unitId:'u',attemptId:'3'}),'REPAIR_BUDGET_EXHAUSTED');f.close();});
test('C49 unknown acceptance never automatically retries',()=>assert.equal(load('budget').retryDecision({kind:'transport',acceptance:'unknown'}),'reconcile'));
test('C50 real queue required before saying queued',()=>{const r=load('read-model').buildProductionView({project:project(),operations:[],readiness:{localPostReady:true,blockers:[],warnings:[]},artifacts:{},streamSeq:0});assert.equal(r.nextAction.id,'start_post');});
test('C51 clean-only artifact is not labelled sfx',()=>{const r=load('read-model').buildProductionView({project:project(),operations:[],readiness:{},artifacts:{clean:{state:'valid',current:true,path:'clean'}},streamSeq:0});assert.equal(r.nextAction.id,'preview_clean');});
test('C52 event gap requires resynchronization',()=>assert.equal(load('read-model').reduceEvent({projectId:'p',streamSeq:1},{projectId:'p',streamSeq:3}).needsResync,true));
function chat(f){return new PromptChatService({repository:f.repo,loadFactsInTransaction:()=>({sourceHash:'S',dialogueRows:[],references:[]})});}
function openChat(f,svc){return svc.createThread({projectId:'p',itemId:'i',commandId:'open',expectedRevision:1,actor}).result.threadId;}
function turnInput(threadId){return {projectId:'p',threadId,clientTurnId:'t1',instruction:'调整情绪',expectedItemRevision:1,expectedContentHash:D.itemHash(prompt()),actor};}
test('C53 duplicate chat reservation gives same operation before any model',()=>{const f=fixture(),svc=chat(f),t=openChat(f,svc),a=svc.reserveTurn(turnInput(t)),b=svc.reserveTurn(turnInput(t));assert.equal(a.operationId,b.operationId);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM operation_outbox').get().n,1);f.close();});
test('C54 same turn ID different instruction rejected',()=>{const f=fixture(),svc=chat(f),t=openChat(f,svc);svc.reserveTurn(turnInput(t));catches(()=>svc.reserveTurn({...turnInput(t),instruction:'另外要求'}),'CHAT_TURN_ID_REUSED');f.close();});
test('C55 history pagination uses real thread_id and seq',()=>{const f=fixture(),svc=chat(f),t=openChat(f,svc);svc.reserveTurn(turnInput(t));const h=svc.getThread({projectId:'p',threadId:t,actor,limit:1});assert.equal(h.messages.length,1);assert.equal(svc.getThread({projectId:'p',threadId:t,actor,afterSeq:h.nextSeq}).messages.length,0);f.close();});
test('C56 cancel queued chat cancels operation; late application prohibited',()=>{const f=fixture(),svc=chat(f),t=openChat(f,svc),r=svc.reserveTurn(turnInput(t));svc.cancelTurn({projectId:'p',threadId:t,turnId:r.turnId,actor});assert.equal(f.db.prepare('SELECT status FROM operation_outbox').get().status,'cancelled');catches(()=>svc.applyProposal({projectId:'p',threadId:t,turnId:r.turnId,commandId:'apply',actor}),'PROPOSAL_NOT_APPLICABLE');f.close();});
test('C57 all large text saved and UTF8 paged without truncation',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'r2-'));try{const body='甲😀乙'.repeat(25000),a=await load('artifact-files').saveFullText(dir,body);assert.equal(await fs.readFile(a.path,'utf8'),body);let offset=0,text='';for(;;){const p=await load('artifact-files').readUtf8Page(a.path,{offset,maxBytes:8192,expectedHash:a.sha256});text+=p.content;offset=p.nextOffset;if(p.complete)break;}assert.equal(text,body);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('C58 migration keeps explicit disabled auto-post and does not mint approval',()=>{const p=project();p.productionV2.options.continueToPost=false;p.promptReview.items[0].userConfirmed=true;const r=load('legacy-migration').migrateProject(p,{sourceRevision:'S',sourceFactHash:'f',policyHash:'p',resolveProviderContract:()=> 'contract',at});assert.equal(r.project.productionV2.options.continueToPost,false);assert.equal(r.project.promptReview.items[0].validation,null);assert.equal(r.project.productionV2.initialApprovalId,undefined);const again=load('legacy-migration').migrateProject(r.project,{});assert.equal(again.changed,false);});
test('C59 SQLite backup is readable and includes committed project state',async()=>{const f=fixture(),dir=await fs.mkdtemp(path.join(os.tmpdir(),'r2-db-'));try{const destination=path.join(dir,'backup.sqlite'),b=load('legacy-migration').backupDatabase(f.db,destination);assert(b.bytes>0);const copy=new DatabaseSync(destination,{readOnly:true});assert.equal(copy.prepare('SELECT COUNT(*) n FROM project_state').get().n,1);copy.close();}finally{f.close();await fs.rm(dir,{recursive:true,force:true});}});
