'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const director=require('../app/agent-production-decisions'),wf=require('../app/workbench-workflow');
test('an inferred continuity relation cannot overwrite the final Agent dialogue decision',()=>{
 const {p,shot,item}=fixture(),event=item.events[0],speech=item.dialogue[0];
 p.filmContinuityPlan={result:{shots:[{shotId:shot.id,actions:[{id:'inferred',speechConstraints:[{dialogueId:speech.id,relation:'before'}]}]}]}};
 event.continuityActionIds=['inferred'];event.throughoutDialogueIds=[speech.id];event.start=speech.start;event.end=speech.end;
 director.apply(p,shot,item);
 assert.deepEqual(shot.agentProductionDecision.item.events[0].speechConstraints,[{dialogueId:speech.id,relation:'covers'}]);
 assert.equal(p.filmContinuityPlan.result.shots[0].actions[0].speechConstraints[0].relation,'before');
});
test('source-grounded offscreen actions do not force a hidden actor into the physical cast',()=>{
 const {p,shot,item}=fixture();p.characters.push({id:'C03',name:'丙'});
 item.events.push({id:'radio',actorIds:['C03'],offscreenActorIds:['C03'],propIds:[],usesProduct:false,start:5,end:7,after:[],descriptionEn:'C03 presses the radio key behind the closed door.',descriptionZh:'丙在关着的门后按住对讲键。'});
 director.apply(p,shot,item);assert.equal(shot.visibleCharacterIds.includes('C03'),false);assert.match(shot.finalPromptEditing.detailedDescriptionEn,/Off-screen participants C03 remain outside the image/);
});
test('offscreen camera disagreements remain visible suggestions for Agent judgment',()=>{
 const {p,shot,item}=fixture();item.events[0].offscreenActorIds=['C01'];assert.equal(director.validate(p,shot,item),true);assert.ok(item.programReviewSuggestions.some(x=>x.includes('offscreen actor is selected by an active camera')));
});
test('offscreen marking accepts only known performing identities',()=>{
 const {p,shot,item}=fixture();item.events[0].offscreenActorIds=['C99'];assert.throws(()=>director.validate(p,shot,item),e=>e.issues.some(x=>x.includes('C99 must be a known character also listed in actorIds')));
});
test('offscreen delivery feedback preserves the source event while explaining both identity lists',()=>{
 const {p,shot,item}=fixture();p.characters.push({id:'C03',name:'丙'});const event=item.events[0];event.offscreenActorIds=['C03'];
 assert.throws(()=>director.validate(p,shot,item),e=>e.issues.some(x=>x.includes('C03 must be a known character also listed in actorIds')));
 event.actorIds.push('C03');assert.equal(director.validate(p,shot,item),true);
 event.offscreenActorIds=[];assert.throws(()=>director.validate(p,shot,item),e=>e.issues.some(x=>x.includes('actorIds AND offscreenActorIds')&&x.includes('do not delete')));
});
test('visible scene furniture remains in the story but never becomes an unproducible image dependency',()=>{
 const {p,shot,item}=fixture();p.assetLibraries.props[0].assetRequired=false;p.assetLibraries.props[0].sourceInventory={classification:'in_scene'};
 director.apply(p,shot,item);
 const refs=wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only');
 assert.equal(refs.images.some(r=>r.type==='prop'&&r.entityId==='P01'),false);
 assert.equal(shot.agentProductionDecision.item.visiblePropIds.includes('P01'),true);
});
test('director response contract leaves source action time to the Agent instead of forcing early speech',()=>{
 const {p,shot}=fixture();
 const rows=director.schema(p,[shot]).properties.items.items.anyOf[0].properties.dialogue.items.anyOf;
 assert.equal(rows[0].properties.id.const,'D01');assert.equal(rows[0].properties.start.maximum,15);
 assert.equal(rows[1].properties.id.const,'D02');assert.equal(rows[1].properties.end.minimum,0);
 assert.equal(rows[0].properties.start.minimum,0,'Agent may start immediately; no artificial opening silence');
 p.script.raw+='播放原稿录音';
 const recorded=director.schema(p,[shot]).properties.items.items.anyOf[0].properties.dialogue.items.anyOf;
 assert.equal(recorded[0].properties.start.maximum,15);assert.equal(recorded[1].properties.end.minimum,0);
});
test('global delivery validation rejects an unsubmitable candidate before marking production complete',async()=>{
 const {p,item}=fixture();item.environmentEn='A detailed physical location. '.repeat(650);let calls=0;
 await assert.rejects(director.author({getProject:()=>structuredClone(p),saveProject:value=>Object.assign(p,value),settings:{textProvider:{}},projectId:'delivery-contract',optionsFor:(_id,_stage,o)=>o,generate:async(_c,m)=>{calls++;if(calls>5)throw Object.assign(Error("cancelled"),{code:"PROVIDER_REQUEST_ABORTED"});const input=JSON.parse(m[1].content);if(input.allowedSourceGroups)return {affectedIds:['S01'],diagnosis:'Bound request exceeds capacity',repairPrompt:'Preserve the source and remove redundant descriptions.'};assert.equal(input.deliveryContracts[0].maxFinalCharacters,10000);return {items:[item]};}}),{code:'PROVIDER_REQUEST_ABORTED'});
 assert.equal(calls,6);assert.equal(p.shots[0].agentProductionDecision,undefined);assert.equal(p.agentProductionDecisionAttempts.length,3);
});
test('native vocal identities are not confused with optional audio-file capacity',()=>{
 const {p,shot,item}=fixture();p.characters.push({id:'C03',name:'丙'});shot.dialogueTurns.push({sourceDialogueId:'D03',speakerId:'C03',speaker:'丙',text:'一二三四五',listenerIds:['C01'],onScreen:true});item.visibleCharacterIds.push('C03');item.states.push({characterId:'C03',openingEn:'Beside the taxi.',openingZh:'车旁。',endingEn:'Beside the taxi.',endingZh:'车旁。'});item.dialogue.push({id:'D03',start:8,end:9,deliveryEn:'Clear and firm.',deliveryZh:'清晰坚定。'});director.apply(p,shot,item);
 const refs=wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only');assert.equal(refs.audios.length,0);assert.equal(require('../app/production-delivery-contract').inspect(p,shot).ok,true);
});
function fixture(){
 const shot={id:'S01',number:1,duration:10,sceneId:'SC01',action:'甲上车完成后，乙启动车辆。甲手里拿着那瓶商品。',stateBefore:'甲在车外，乙在驾驶位',stateAfter:'两人在车内',characterIds:['C01','C02'],visibleCharacterIds:['C01','C02'],dialogueTurns:[{sourceDialogueId:'D01',speakerId:'C01',text:'一二三四五六七八九十',sourceTone:'清楚',listenerIds:['C02'],onScreen:true},{sourceDialogueId:'D02',speakerId:'C02',text:'甲乙丙丁戊己庚辛壬癸',sourceTone:'清楚',listenerIds:['C01'],onScreen:true}]};
 const p={script:{raw:shot.action},generation:{engine:'hailuo-h3',mode:'asset_direct'},product:{name:'示例商品',imagePath:__filename},characters:[{id:'C01',name:'甲'},{id:'C02',name:'乙'}],scenes:[{id:'SC01',name:'路边'}],assetLibraries:{props:[{id:'P01',name:'出租车'}]},shots:[shot]};
 const item={shotId:'S01',duration:10,visibleCharacterIds:['C01','C02'],visiblePropIds:['P01'],productVisible:true,states:['C01','C02'].map(id=>({characterId:id,openingEn:'At the parked taxi.',openingZh:'在停着的车旁。',endingEn:'Inside the moving taxi.',endingZh:'在行驶的车内。'})),environmentEn:'A quiet road and one taxi P01.',environmentZh:'安静路边和一辆出租车。',events:[{id:'board',actorIds:['C01'],propIds:['P01'],usesProduct:true,start:.3,end:3,after:[],descriptionEn:'C01 climbs into P01 holding the product and shuts the door.',descriptionZh:'甲持商品上车关门。'},{id:'drive',actorIds:['C02'],propIds:['P01'],usesProduct:false,start:3.5,end:9,after:['board'],descriptionEn:'C02 drives P01 along the road.',descriptionZh:'乙驾车驶上道路。'}],cameras:[{at:0,size:'medium',angle:'left-front',movement:'locked',subjectIds:['C01','C02']},{at:4,size:'medium',angle:'left-front',movement:'slow push-in',subjectIds:['C01','C02']}],dialogue:[{id:'D01',start:1,end:3,deliveryEn:'Urgent and clear.',deliveryZh:'焦急清晰。'},{id:'D02',start:5,end:7,deliveryEn:'Calm and firm.',deliveryZh:'沉稳坚定。'}],summaryEn:'A passenger boards before departure.',soundscapeEn:'Quiet traffic hum and continuous engine rumble.'};return {p,shot,item};
}
test('speech isolation does not prohibit source-authored eating after dialogue in either language',()=>{
 const {p,shot,item}=fixture();item.events.push({id:'bite',actorIds:['C01'],propIds:[],usesProduct:false,start:8,end:8.8,after:['board'],descriptionEn:'C01 opens his mouth for one bite and then closes his lips to chew.',descriptionZh:'甲张嘴吃一口，然后闭唇咀嚼。'});
 director.apply(p,shot,item);assert.deepEqual(shot.agentProductionDecision.item.events,item.events);assert.deepEqual(shot.agentProductionDecision.item.dialogue,item.dialogue);
 const en=shot.finalPromptEditing.detailedDescriptionEn,zh=shot.finalPromptEditing.detailedDescriptionZh;
 assert.match(en,/opens his mouth for one bite/);assert.match(en,/no additional live speech or speech lip-sync/);assert.doesNotMatch(en,/all mouths remain closed|All other visible mouths remain closed/);
 assert.match(zh,/甲张嘴吃一口/);assert.match(zh,/不再有现场对白或说话口型/);assert.doesNotMatch(zh,/所有人物仅.*台词时段开口|所有.*保持闭口/);
});
test('agent-selected product survives generic nouns without keyword inference and explicit hidden selection is respected',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);assert.equal(director.current(p,shot),true);assert.equal(wf.shotVideoProductReferenceRequired(p,shot),true);assert.ok(wf.promptReviewReferencePlan(p,shot,'asset_direct').imageRoles.some(r=>r.type==='product'));shot.videoReferenceIncludeProduct=false;assert.equal(wf.shotVideoProductReferenceRequired(p,shot),true,'obsolete override must not contradict the current agent decision');});
test('dependency timing disagreement is an Agent suggestion rather than a creative veto',()=>{const {p,shot,item}=fixture();item.events[1].start=2;assert.equal(director.validate(p,shot,item),true);assert.ok(item.programReviewSuggestions.some(i=>i.includes('prerequisite board')));});
test('camera focus is serialized from selected IDs without inventing people or excluding source-present listeners',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);assert.match(shot.finalPromptEditing.detailedDescriptionEn,/camera focus: C01, C02/);assert.doesNotMatch(shot.finalPromptEditing.detailedDescriptionEn,/three figures|visible people:/);assert.match(shot.finalPromptEditing.detailedDescriptionEn,/does not remove other source-present people/);item.cameras[1].subjectIds.push('C03');assert.throws(()=>director.validate(p,shot,item),e=>e.issues.some(i=>i.includes('physical cast')));});
test('dialogue words and speaker owners survive deterministic assembly and real provider binding',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);const refs=wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only');const prompt=wf.renderApprovedVideoPrompt(p,shot,refs);assert.equal((prompt.match(/<d>/g)||[]).length,2);assert.ok(prompt.includes('一二三四五六七八九十'));assert.equal(wf.assertHailuoPromptVoiceBindings(p,shot,refs,prompt),true);});
test('source edits invalidate decisions while regenerating display prose does not',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);shot.finalPromptEditing.summaryEn='Another display summary';assert.equal(director.current(p,shot),true);shot.action+='改变原稿。';assert.equal(director.current(p,shot),false);});
test('master decisions replace old body metadata rather than letting normalization revive contradictions',()=>{const {p,shot,item}=fixture();shot.dialogueTurns[0].metadata={bodyEn:'Drive before boarding.'};director.apply(p,shot,item);assert.equal(shot.dialogueTurns[0].metadata.bodyEn,undefined);assert.equal(shot.sourcePerformanceBudget.source,'master-agent-decision');});
test('Codex schema transport fills required types and restores optional absence without changing required false',()=>{const c=require('../app/codex-output-schema'),s={type:'object',properties:{id:{const:'S01'},ok:{enum:[true,false]},note:{type:'string'}},required:['id','ok'],additionalProperties:false},before=JSON.stringify(s),n=c.prepare(s);assert.equal(n.properties.id.type,'string');assert.equal(n.properties.ok.type,'boolean');assert.deepEqual(n.required,['id','ok','note']);assert.deepEqual(c.restore({id:'S01',ok:false,note:null},s),{id:'S01',ok:false});assert.equal(JSON.stringify(s),before);});
test('workflow invokes one master author and final preparation reuses that decision without another writer',async()=>{const {p,item}=fixture();let calls=0,project=p;const settings={generation:{agentDecisionAuthority:true},textProvider:{}},store={getProject:()=>project,saveProject:v=>(project=v),getSettings:()=>settings};const flow=new wf.WorkbenchWorkflow({store,bridge:{}});flow.setAutomation=()=>{};flow.analyzeScript=async()=>project; // Intake has its own real routing regression; isolate director reuse here.
flow.productionTextOptions=(_id,_stage,opts)=>opts;flow.generateText=async()=>{calls++;return {items:[item]};};await flow.compileH3AssetDirectSemanticsBatch('test',settings);await flow.authorFinalH3PromptBlocks('test');assert.equal(calls,1);assert.equal(project.h3AssetDirectSemanticCompile.source,'master-agent-decision');assert.equal(project.shots[0].finalPromptEditing.source,'master-agent-decision');});
test('unsupported native regex is omitted only from transport and remains enforced after response',()=>{const schema={type:'string',pattern:'^(?!bad).+'},native=require('../app/codex-output-schema').prepare(schema),project=require('../app/typed-output-projection').project;assert.equal(native.properties.codex_payload.pattern,undefined);assert.equal(schema.pattern,'^(?!bad).+');assert.equal(project('bad result',schema),undefined);assert.equal(project('good result',schema),'good result');});
test('open audit evidence objects survive native serialization instead of becoming empty objects',()=>{const c=require('../app/codex-output-schema'),s={type:'array',items:{type:'object',additionalProperties:true}},value={check:'causality',ok:false,evidence:{shot:'S01',quote:'original'}};assert.equal(c.prepare(s).properties.codex_payload.items.type,'string');assert.deepEqual(c.restore([JSON.stringify(value)],s),[value]);assert.equal(require('../app/typed-output-projection').project(c.restore(['not json'],s),s),undefined);});
test('Codex terminal failures retain schema versus quota versus authentication causes',()=>{const r=require('../app/local-agent-runtime');for(const [message,code]of [['invalid_json_schema','LOCAL_AGENT_SCHEMA_UNSUPPORTED'],['usage limit','LOCAL_AGENT_QUOTA'],['authentication failed','LOCAL_AGENT_AUTH_REQUIRED']])assert.throws(()=>r.finalEvent({type:'turn.failed',error:{message}}),{code});});
test('native root unions are wrapped and negative reviewer findings are restored intact',()=>{const c=require('../app/codex-output-schema'),s={anyOf:[true,false].map(ok=>({type:'object',properties:{ok:{const:ok},checks:{type:'array',items:{type:'object',additionalProperties:true}}},required:['ok','checks'],additionalProperties:false}))};const n=c.prepare(s);assert.equal(n.type,'object');assert.equal(n.anyOf,undefined);const r=c.restore({codex_payload:{ok:false,checks:['{"reason":"causal order reversed"}']}},s);assert.deepEqual(r,{ok:false,checks:[{reason:'causal order reversed'}]});assert.notEqual(require('../app/typed-output-projection').project(r,s),undefined);});
test('legacy annotation changes cannot invalidate the authoritative master body and revive old staging',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);shot.providerTimedDirections=[{actionEn:'Leave before boarding'}];shot.dialogueTurns[0].bodyEn='Drive away before boarding';assert.equal(require('../app/h3-final-prompt-editor').current(shot),true);const prompt=wf.renderApprovedVideoPrompt(p,shot,wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only'));assert.doesNotMatch(prompt,/Drive away before boarding|Leave before boarding/);assert.match(prompt,/climbs into/);});
test('duplicate audit rows retain every finding with unique verification IDs',()=>{const e=require('../app/prompt-review-evidence'),v=require('../app/prompt-finding-verification'),items=[{id:'shot:S01:shot_video',entityType:'shot',entityId:'S01',prompt:'The wrong event.'}],facts=e.catalog({shots:[{id:'S01',action:'Correct event.'}]}),fact=facts.find(f=>f.text==='Correct event.'),issue={sourceFactId:fact.id,promptFactId:'P1L1',contradiction:'Wrong event',repair:'Use correct event'},bound=e.bind({items:[{id:items[0].id,issues:[issue]},{id:items[0].id,issues:[{...issue,contradiction:'Wrong actor'}]}]},facts,items);assert.equal(bound.items.length,1);assert.equal(bound.items[0].issues.length,2);assert.equal(new Set(v.prepare(bound).map(f=>f.id)).size,2);assert.equal(e.schema(facts,items).properties.items.maxItems,1);});
test('source-recorded speech becomes exact offscreen audio rather than an English paraphrase',()=>{const {p,shot,item}=fixture();p.script.raw+='录音里甲说：“等等。”';item.events.push({id:'playback',actorIds:['C01'],propIds:[],usesProduct:false,start:3.2,end:3.6,after:['board'],descriptionEn:'The established recording plays.',descriptionZh:'播放既定录音。',recordedSpeech:{speakerId:'C01',textZh:'等等。',sourceQuoteZh:'录音里甲说：“等等。”',deliveryEn:'Urgent recorded voice.',deliveryZh:'焦急的录音声音。'}});director.apply(p,shot,item);const refs=wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only'),prompt=wf.renderApprovedVideoPrompt(p,shot,refs);assert.equal((prompt.match(/<d>/g)||[]).length,3);assert.match(prompt,/<d>\[Chinese\] 等等。<\/d>/);assert.match(prompt,/voice-over from the in-scene recording/);assert.equal(wf.assertHailuoPromptVoiceBindings(p,shot,refs,prompt),true);item.events.at(-1).recordedSpeech.textZh='不存在的台词';assert.throws(()=>director.validate(p,shot,item),e=>e.issues.some(i=>i.includes('quote original source')));});
test('Agent clip duration and exact authored speech windows remain unchanged',()=>{const {p,shot,item}=fixture();item.dialogue[0].start=3;item.dialogue[0].end=5;item.dialogue[1].start=7.67;item.dialogue[1].end=9.67;item.cameras=[item.cameras[0]];director.apply(p,shot,item);assert.equal(shot.duration,10);assert.equal(shot.dialogueTurns[1].end,9.67);assert.equal(item.duration,10);});
test('a prohibition on subtitles is not rejected as a subtitle request by the wire validator',()=>{const {p,shot,item}=fixture();item.environmentEn+=' The scene has no added timestamps, subtitles or overlays.';director.apply(p,shot,item);assert.doesNotThrow(()=>wf.renderApprovedVideoPrompt(p,shot,wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only')));});

test('whole-film clocks fit within contract without changing events, words or cast',()=>{
 const {p,shot,item}=fixture();director.apply(p,shot,item);
 p.script.runtimePolicy={targetSeconds:11,minSeconds:11,maxSeconds:11};
 const prior=structuredClone(shot.agentProductionDecision.item),words=shot.dialogueTurns.map(t=>t.text);
 assert.equal(require('../app/film-production-clock').fit(p,director),true);
 assert.equal(p.shots[0].duration,11);assert.deepEqual(p.shots[0].dialogueTurns.map(t=>t.text),words);
 assert.deepEqual(p.shots[0].agentProductionDecision.item.visibleCharacterIds,prior.visibleCharacterIds);
 p.shots[0].agentProductionDecision.item.events.forEach((e,i)=>{assert.equal(e.descriptionEn,prior.events[i].descriptionEn);assert.deepEqual(e.after,prior.events[i].after);assert.ok(Math.abs((e.end-e.start)-(prior.events[i].end-prior.events[i].start))<.001);});
 assert.equal(director.current(p,p.shots[0]),true);assert.equal(require('../app/film-production-clock').fit(p,director),false);
});
test('infeasible whole-film clock is atomic and cannot approve a partial result',()=>{
 const {p,shot,item}=fixture();director.apply(p,shot,item);p.script.runtimePolicy={targetSeconds:20,minSeconds:20,maxSeconds:20};const before=JSON.stringify(p);
 assert.throws(()=>require('../app/film-production-clock').fit(p,director),{code:'FILM_RUNTIME_EXECUTION_INFEASIBLE'});assert.equal(JSON.stringify(p),before);
});

test('authoring entry preserves the Agent clock instead of forcing the planning estimate',async()=>{
 const {p,item}=fixture();p.script.runtimePolicy={targetSeconds:11,minSeconds:11,maxSeconds:11};let project=p,plans=0,workers=0;
 await director.author({getProject:()=>project,saveProject:x=>(project=x),settings:{textProvider:{}},projectId:'test',optionsFor:(_id,_stage,options)=>options,generate:async(_c,_m,options)=>{if(options.stage==='film_runtime_director_plan'){plans++;return {feasible:true,shotBudgets:[{shotId:'S01',maxSeconds:11,performanceDirection:'Complete boarding before driving; retain every spoken line.'}],issues:[]};}workers++;return {items:[item]};}});
 assert.equal(plans,1);assert.equal(workers,1);assert.equal(project.shots[0].duration,10);assert.equal(project.script.filmClockReceipt,undefined);assert.match(project.shots[0].finalPromptEditing.detailedDescriptionEn,/Physical event/);
});

test('whole-film director plans a source-faithful targeted performance repair before worker execution',async()=>{
 const {p,item}=fixture();p.shots[0].dialogueTurns[1].text=p.shots[0].dialogueTurns[1].text.repeat(3);
 const long=structuredClone(item);long.duration=13;long.events[1].end=12;long.dialogue[0].start=2;long.dialogue[0].end=4;long.dialogue[1].start=7;long.dialogue[1].end=11;
 const short=structuredClone(item);short.dialogue[1].end=9;
 director.apply(p,p.shots[0],long);p.script.runtimePolicy={targetSeconds:10,minSeconds:10,maxSeconds:10};let project=p,plans=0,workers=0;
 const words=p.shots[0].dialogueTurns.map(t=>t.text);
 await director.author({getProject:()=>project,saveProject:x=>(project=x),settings:{textProvider:{}},projectId:'test',optionsFor:(_id,_stage,options)=>options,generate:async(_c,m,options)=>{if(options.stage==='film_runtime_director_plan'){plans++;return {feasible:true,shotBudgets:[{shotId:'S01',maxSeconds:10,performanceDirection:'Board during the first spoken line; start driving only after boarding ends.'}],issues:[]};}workers++;assert.match(m[1].content,/FILM_DIRECTOR_PERFORMANCE_PLAN/);return {items:[short]};}});
 assert.equal(plans,1);assert.equal(workers,1);assert.equal(project.shots[0].duration,10);assert.deepEqual(project.shots[0].dialogueTurns.map(t=>t.text),words);assert.equal(project.script.directorRuntimePlan.settledTotalSeconds,10);
});

test('whole-film duration disagreement preserves the complete candidate and advice without retrying writers',async()=>{
 const {p,item}=fixture();p.shots[0].dialogueTurns[1].text=p.shots[0].dialogueTurns[1].text.repeat(3);const long=structuredClone(item);long.duration=13;long.events[1].end=12;long.dialogue[0].start=2;long.dialogue[0].end=4;long.dialogue[1].start=7;long.dialogue[1].end=11;p.script.runtimePolicy={targetSeconds:10,minSeconds:10,maxSeconds:10};let project=p,plans=0,workers=0;
 await director.author({getProject:()=>project,saveProject:x=>(project=x),settings:{textProvider:{}},projectId:'advisory-budget',optionsFor:(_id,_stage,o)=>o,generate:async(_c,m,o)=>{if(o.stage==='film_runtime_director_plan'){plans++;return {feasible:true,shotBudgets:[{shotId:'S01',maxSeconds:10,performanceDirection:'Preserve source.'}],issues:[]};}workers++;return {items:[long]};}});
 assert.equal(plans,1);assert.equal(workers,1);assert.equal(project.shots[0].agentProductionDecision.item.duration,13);assert.equal(project.script.directorRuntimeConflicts[0].validCandidateSeconds,13);assert.equal(project.script.directorRuntimePlan.settledTotalSeconds,13);
});

test('master dialogue clocks survive a real WorkbenchStore save and reload despite obsolete metadata outside the new clip',()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{WorkbenchStore}=require('../app/workbench-store');
 const tempParent=fs.realpathSync(os.tmpdir()),root=fs.mkdtempSync(path.join(tempParent,'director-clock-store-'));
 try{
  const store=new WorkbenchStore(root),created=store.createProject('主导演时窗真实落盘回归'),{p,item}=fixture();
  let project=Object.assign(created,p);project.shots[0].duration=15;
  project.shots[0].dialogueTurns.forEach((t,i)=>{t.start=t.startSecond=i?11:8;t.end=t.endSecond=i?13.32:10;t.metadata={startSecond:t.startSecond,endSecond:t.endSecond,sourceTone:'清楚'};});
  store.saveProject(project);project=store.getProject(project.id);director.apply(project,project.shots[0],item);store.saveProject(project);
  const loaded=store.getProject(project.id),shot=loaded.shots[0];assert.equal(shot.duration,10);
  shot.dialogueTurns.forEach((t,i)=>{const expected=item.dialogue[i];assert.equal(t.start,expected.start);assert.equal(t.end,expected.end);assert.equal(t.startSecond,expected.start);assert.equal(t.endSecond,expected.end);assert.equal(t.metadata.startSecond,expected.start,'obsolete metadata must not remain available to revive old start times');assert.equal(t.metadata.endSecond,expected.end,'obsolete metadata must not remain available to revive old end times');assert.ok(t.endSecond<=shot.duration-.35);});
  assert.equal(director.current(loaded,shot),true);assert.doesNotThrow(()=>director.validate(loaded,shot,shot.agentProductionDecision.item));
 }finally{const resolved=fs.realpathSync(root);assert.ok(resolved.startsWith(tempParent+path.sep)&&path.basename(resolved).startsWith('director-clock-store-'));fs.rmSync(resolved,{recursive:true,force:true});}
});

test('editorial timing uses current master dialogue IDs and events instead of stale legacy clocks, and stops trusting master after source edits',()=>{
 const {p,shot,item}=fixture(),ed=require('../app/commerce-editorial-contract');director.apply(p,shot,item);
 shot.dialogueTurns.forEach((t,i)=>{t.start=t.startSecond=11+i;t.end=t.endSecond=13.32+i;t.metadata={...t.metadata,startSecond:t.startSecond,endSecond:t.endSecond};});
 shot.subshots=[{action:'过期分镜动作，不应参与当前审核',start:14,end:18}];
 assert.equal(director.current(p,shot),true);const current=ed.projectUnits(p);
 assert.equal(ed.timingReady(current),true);assert.deepEqual(current[0].turns.map(t=>[t.start,t.end]),item.dialogue.map(d=>[d.start,d.end]));
 assert.deepEqual(current[0].actions,item.events.map(e=>({text:e.descriptionZh,start:e.start,end:e.end})));assert.doesNotMatch(current[0].text,/过期分镜动作/);
 shot.dialogueTurns[0].text+='用户新改的台词';assert.equal(director.current(p,shot),false);
 const changed=ed.projectUnits(p);assert.equal(ed.timingReady(changed),false);assert.equal(changed[0].turns[0].start,11);assert.equal(changed[0].actions[0].text,'过期分镜动作，不应参与当前审核');assert.match(changed[0].turns[0].text,/用户新改的台词/);
});

test('canonical recorded dialogue is bound once and cannot be duplicated as extra speech',()=>{const {p,shot,item}=fixture();const t=shot.dialogueTurns[0];item.events.push({id:'playback',actorIds:['C01'],propIds:[],usesProduct:false,start:1,end:3,after:[],throughoutDialogueIds:['D01'],descriptionEn:'Play the canonical recorded line once.',descriptionZh:'播放原对白录音一次。',recordedSpeech:{speakerId:'C01',textZh:t.text,sourceQuoteZh:'A model summary is not needed for canonical dialogue.',deliveryEn:'Recorded voice.',deliveryZh:'录音声音。'}});assert.deepEqual(director.recordedDialogueIds(shot,item.events.at(-1)),['D01']);director.apply(p,shot,item);const prompt=wf.renderApprovedVideoPrompt(p,shot,wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only'));assert.equal((prompt.match(/<d>/g)||[]).length,2);assert.match(prompt,/in-scene recording/);});
test('a missing product image is a media preparation todo and cannot block written staging',()=>{const {p,shot,item}=fixture();delete p.product.imagePath;assert.equal(director.validate(p,shot,item),true);assert.ok(item.programReviewSuggestions.some(x=>x.includes('Upload the original product image before media generation')));});

test('Codex websocket interruption uses the existing bounded same-model text recovery',async()=>{const r=require('../app/local-agent-runtime');const event={type:'error',message:'Reconnecting... 2/5 (stream disconnected before completion: WebSocket protocol error: Connection reset without closing handshake)'};assert.throws(()=>r.finalEvent(event),{code:'LOCAL_AGENT_TRANSPORT_INTERRUPTED'});});

test('Agent-selected addressees and stationary object end states survive executable rendering',()=>{const {p,shot,item}=fixture();item.dialogue[0].listenerIds=['C02'];item.dialogue[0].addressMode='person';item.objectStates=[{propId:'P01',openingEn:'The taxi is supported by its four tires on the road.',openingZh:'出租车四轮接地。',endingEn:'The taxi remains supported by its four tires on the road.',endingZh:'出租车仍四轮接地。'}];director.apply(p,shot,item);const prompt=wf.renderApprovedVideoPrompt(p,shot,wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only'));assert.match(prompt,/addresses <Subject 2>/);assert.doesNotMatch(prompt,/authored listener/);assert.match(prompt,/remains supported by its four tires/);const s=director.schema(p,[shot]).properties.items.items.anyOf[0];assert.ok(s.required.includes('objectStates'));assert.ok(s.properties.dialogue.items.anyOf[0].required.includes('listenerIds'));});
test('source wardrobe and prop bindings invalidate the authored decision when changed',()=>{const {p,shot,item}=fixture();director.apply(p,shot,item);shot.wardrobeLabel='old work outfit';assert.equal(director.current(p,shot),false);});

test('recorded dialogue references avoid free text duplication and bind only canonical same-voice identities',()=>{const {p,shot,item}=fixture();item.events.push({id:'recorded',actorIds:['C01'],propIds:[],usesProduct:false,start:1,end:3,after:[],descriptionEn:'The canonical recording plays once.',descriptionZh:'原对白录音播放一次。',recordedSpeech:{speakerId:'C01',sourceDialogueIds:['D01'],deliveryEn:'Recorded.',deliveryZh:'录音。'}});assert.deepEqual(director.recordedDialogueIds(shot,item.events.at(-1)),['D01']);director.apply(p,shot,item);const prompt=wf.renderApprovedVideoPrompt(p,shot,wf.promptReviewReferencePlan(p,shot,'asset_direct','image_only'));assert.equal((prompt.match(/<d>/g)||[]).length,2);item.events.at(-1).recordedSpeech.sourceDialogueIds=['D02'];assert.throws(()=>director.validate(p,shot,item));});

test('runtime preferences cannot block asset and prompt preparation but transport failures remain actionable',async()=>{const d=require('../app/film-runtime-director'),{p}=fixture();p.script.runtimePolicy={targetSeconds:10,minSeconds:10,maxSeconds:15};let saved=false;const opts={project:p,getProject:()=>p,generate:async()=>({feasible:false,shotBudgets:[],issues:['Source pauses exceed the preferred runtime.']}),save:async()=>{saved=true}};assert.equal(await d.planForPreparation(opts),null);assert.equal(saved,true);assert.equal(p.script.runtimePlanningAdvisory.code,'FILM_RUNTIME_DIRECTOR_INFEASIBLE');p.script.raw+='new revision';await assert.rejects(d.planForPreparation({...opts,generate:async()=>{throw Object.assign(Error('offline'),{code:'NETWORK_OFFLINE'})}}),{code:'NETWORK_OFFLINE'});});

test('MCP preview measures the bound request without mutating source and blocks an oversized commit',()=>{const {p,item}=fixture();const original=JSON.stringify(p);const preview=require('../app/mcp/stage-preview');const request={deliveryPreview:{kind:'master-production-decision',project:p}};const good=preview.preview(request,{data:{items:[item]}});assert.equal(good.ok,true);assert.ok(good.items[0].prompt.includes(p.shots[0].dialogueTurns[0].text));assert.equal(good.items[0].characters,good.items[0].prompt.length);assert.equal(JSON.stringify(p),original);item.environmentEn='Long description. '.repeat(1000);const bad=preview.preview(request,{data:{items:[item]}});assert.equal(bad.ok,false);assert.ok(bad.items[0].characters>10000);assert.equal(bad.items[0].characters,bad.items[0].prompt.length);assert.equal(JSON.stringify(p),original);assert.equal(preview.preview(request,{data:{items:[]}}).ok,false);});

test('explicit asset decisions and exact provider requests survive a real store round trip in every mode',t=>{const fs=require('fs'),os=require('os'),path=require('path'),{WorkbenchStore}=require('../app/workbench-store');const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-assets-roundtrip-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const store=new WorkbenchStore(root,{encode:x=>x,decode:x=>x});for(const mode of ['asset_direct','keyframe','storyboard_sheet']){const {p,item}=fixture();p.generation.mode=mode;p.assetLibraries.props[0].assetRequired=false;p.assetLibraries.props[0].units=['ordinary object label'];p.characters[0].gender='female';p.characters[0].appearanceDescription='Source-authored appearance, preserved literally.';const base=store.createProject(mode);Object.assign(p,{id:base.id});store.saveProject({...base,...p});Object.assign(p,store.getProject(p.id));director.apply(p,p.shots[0],item);const refs=wf.promptReviewReferencePlan(p,p.shots[0],mode,'image_only'),before=wf.renderApprovedVideoPrompt(p,p.shots[0],refs);store.saveProject(p);const read=store.getProject(p.id);assert.equal(read.assetLibraries.props[0].assetRequired,false);assert.deepEqual(read.assetLibraries.props[0].units,['ordinary object label']);assert.equal(read.characters[0].gender,'female');assert.equal(read.characters[0].appearanceDescription,p.characters[0].appearanceDescription);assert.equal(director.current(read,read.shots[0]),true);const after=wf.renderApprovedVideoPrompt(read,read.shots[0],wf.promptReviewReferencePlan(read,read.shots[0],mode,'image_only'));assert.equal(after,before);}});

test('an overflowing dialogue clock is returned to its Agent without trimming words or changing duration',()=>{const {p,item}=fixture();item.dialogue[1].end=10.2;const before=JSON.stringify(p);const result=require('../app/mcp/stage-preview').preview({deliveryPreview:{kind:'master-production-decision',project:p}},{data:{items:[item]}});assert.equal(result.ok,false);assert.match(result.items[0].issues.join(' '),/inside the submitted clip/);assert.equal(JSON.stringify(p),before);assert.equal(item.dialogue[1].end,10.2);assert.equal(item.duration,10);});

test('dialogue serialization preserves Agent group/self/offscreen addressing with exact named listeners',()=>{
 for(const [mode,listeners,phrase] of [['group',['C02'],'addresses the source-authored group, including C02'],['group',[],'addresses the source-authored group'],['person',['C02'],'addresses C02'],['self',[],'speaks to oneself'],['offscreen',['C02'],'addresses the off-screen recipient C02'],['viewer',[],'faces the viewer through the lens']]){
  const {p,shot,item}=fixture();shot.dialogueTurns[0].addressMode=mode;shot.dialogueTurns[0].listenerIds=listeners;item.dialogue[0].addressMode=mode;item.dialogue[0].listenerIds=listeners;const text=shot.dialogueTurns[0].text,decision=JSON.stringify(item);director.apply(p,shot,item);assert.ok(shot.finalPromptEditing.detailedDescriptionEn.includes(phrase),mode);assert.equal(shot.dialogueTurns[0].text,text);assert.equal(JSON.stringify(item),decision,'serialization never changes the authored decision');assert.equal(shot.finalPromptEditing.renderVersion,5);
 }
});
