'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const policy=require('../app/commerce-authoring-policy'),editorial=require('../app/commerce-editorial-contract'),{author}=require('../app/first-pass-script-author');
const {topicProductReadiness,productionHardContractFailures}=require('../app/workbench-workflow');
const product={name:'折叠雨伞'};
const lines=['阿青（对母亲；焦急；抱住书包）：妈，我怕书包里的卷子又被雨淋湿。','母亲（对阿青；认真；接住书包）：你要随身能带着的，才不会走到半路才发现没伞。','母亲（对阿青；温和；手持折叠雨伞）：这把折叠雨伞，收好以后放包里，走到哪儿都能记着带。','阿青（对母亲；释然；双手接稳雨伞）：我把它放到包里，明天陪你一起去学校。','母亲（对观众；清晰；持伞和女儿一同看向镜头）：也有这个需要的，可以看看商品详情，再决定适不适合自己。'];
const profile={category:'雨伞',referencePattern:'care_demonstration',sellingPoints:[{text:'折叠后方便随身携带',basis:'category_use',evidence:'折叠雨伞'}],storyBridge:'母亲发现女儿怕卷子淋湿，选择可收纳随身携带的雨伞'};
const output=()=>({plan:{title:'那把伞',logline:'母女化解误会',cast:[{name:'阿青',role:'女儿'},{name:'母亲',role:'母亲'}],locations:[{name:'门厅'}],scenes:[{id:'S01',location:'门厅'}],ending:'相伴'},parts:[{sceneId:'S01',scriptText:lines.join('\n'),endState:'阿青持雨伞，母女留在门厅'}],commerceProfile:structuredClone(profile)});
const q=i=>({unitId:'S01',quote:lines[i]});
const review=()=>({ok:true,issues:[],checks:[{dimension:'continuity',evidence:lines[1]}],openingCheck:{ok:true,quote:lines[0],bond:'母女',reason:'担心卷子淋雨'},editorial:{checks:editorial.DIMENSIONS.map(d=>({dimension:d,ok:true,explanation:'原文可定位',evidence:[q(2)]})),anchors:{need:q(0),selection:q(1),introduction:q(2),ctaTransition:q(3),cta:q(4)},featureEvidence:[{...q(2),fact:profile.sellingPoints[0].text}],intervals:[]}});
for(const mode of ['asset_direct','keyframe','continuation','smart','storyboard_sheet'])test(`one complete generation and one review in ${mode}`,async()=>{const stages=[];const result=await author({topic:{id:'t'},product,commerceMode:'explicit',productionMode:mode,generate:async(m,o)=>{stages.push(o.stage);assert.equal(o.maxAttempts,1);return stages.length===1?output():review();}});assert.equal(result.status,'ready');assert.deepEqual(stages,['adaptive_script_complete','adaptive_script_review_first_pass']);assert.equal(result.firstPass.generationCalls,1);assert.equal(result.firstPass.automaticRewriteCalls,0);assert.equal(result.commerceProfile.referencePattern,'care_demonstration');});
test('missing selling points and optional offer do not block product-name plus uploaded-image input',()=>{const p={ideation:{commerceMode:'explicit'},commerceMode:'explicit',product:{name:'折叠雨伞',imagePath:__filename}};const r=topicProductReadiness(p);assert.equal(r.ready,true);});
test('all 25 reference cases are covered, 19 commerce and 6 noncommerce',()=>{const r=require('../app/commerce-reference-cases.json');assert.equal(r.cases.length,25);assert.equal(r.cases.filter(c=>c.hasCommerce).length,19);for(const c of r.cases){assert.match(c.sourceSha256,/^[a-f0-9]{64}$/);if(c.hasCommerce)assert.ok(Object.hasOwn(policy.PATTERNS,c.mechanism));}});
test('placeholders never become supplied facts; explicit facts survive inference',()=>{assert.deepEqual(policy.suppliedFacts({description:'根据产品特性自由编辑'}),[]);assert.deepEqual(policy.acceptedFacts({...product,sellingPoints:'伞面黄色',commerceProfile:profile}),['伞面黄色','折叠后方便随身携带']);});
test('unsupported medical and price inference cannot become accepted facts',()=>{for(const text of ['能够治疗头痛','保证不漏雨','只要39元']){const bad={...profile,sellingPoints:[{text,basis:'category_use',evidence:'折叠雨伞'}]};assert.ok(policy.validateProfile(bad,product).length);assert.deepEqual(policy.acceptedFacts({...product,commerceProfile:bad}),[]);}});
test('negative first-pass review is cached without an automatic rewrite or paid review replay',async()=>{let calls=0;const options={topic:{id:'t'},product,commerceMode:'explicit',generate:async()=>++calls===1?output():{...review(),ok:false,issues:[{sceneId:'S01',message:'实际道具连续性错误'}]}};const result=await author(options);assert.equal(result.status,'needs_review');assert.equal(calls,2);const again=await author({...options,checkpoint:result});assert.equal(calls,2);assert.equal(again.status,'needs_review');});
test('incomplete first pass retains evidence without silently generating the missing half',async()=>{let calls=0,saved;await assert.rejects(author({topic:{},product,commerceMode:'explicit',save:s=>saved=structuredClone(s),generate:async()=>{calls++;const r=output();r.parts=[];return r;}}),{code:'SCRIPT_FIRST_PASS_INCOMPLETE'});assert.equal(calls,1);assert.equal(saved.firstPass.generationCalls,1);});
test('first-pass noncommerce does not require invented product facts',async()=>{let n=0;const r=await author({topic:{id:'n'},commerceMode:'none',generate:async()=>++n===1?output():review()});assert.equal(r.status,'ready');assert.equal(n,2);});
test('standalone product top and subshots are rejected at short and long film lengths',()=>{for(const count of [1,30]){const bad={shots:Array.from({length:count},(_,i)=>({id:'S'+(i+1),duration:10,productMention:true,productShotType:'product_detail',visibleCharacterIds:[],subshots:[]}))};assert.ok(productionHardContractFailures(bad,{requireDialogueTables:false,requireHook:false,requireProduct:false}).some(i=>i.code==='PRODUCT_CHARACTER_CONTEXT_REQUIRED'));}const base={id:'S1',productMention:true,visibleCharacterIds:['C01'],subshots:[{shotType:'product_detail',visibleCharacterIds:[]}]};assert.equal(policy.characterProductIssues([base]).length,1);base.subshots[0].visibleCharacterIds=['C01'];assert.equal(policy.characterProductIssues([base]).length,0);});
test('frontend uses same optional selling-point rule and preserves mandatory image/name',()=>{const source=fs.readFileSync(require.resolve('../app/renderer/workbench.js'),'utf8');const body=source.match(/function topicProductPrerequisiteGaps\([^]*?\n\}/)[0];const context={state:{project:{}},topicCommerceMode:()=> 'explicit',currentTopicProductContext:()=>({name:'伞',imagePath:'test.png'})};vm.createContext(context);vm.runInContext(body,context);assert.equal(context.topicProductPrerequisiteGaps().length,0);context.currentTopicProductContext=()=>({});assert.equal(context.topicProductPrerequisiteGaps().length,2);});
test('effective saved/default rules contain no mandatory standalone product inserts',()=>{const {defaultPromptTemplates}=require('../app/prompt-library');for(const [key,value]of Object.entries(defaultPromptTemplates())){if(typeof value==='string')assert.doesNotMatch(value,/商品整体\/细节干净镜只能|整体\/细节镜不得被人脸|必须\s*visibleCharacterIds=\[\]/,key);}const source=fs.readFileSync(require.resolve('../app/workbench-workflow'),'utf8');assert.doesNotMatch(source,/PRODUCT_CLEAN_SHOT_FACE_INTRUSION|PRODUCT_PACKSHOT_MISSING/);
 // The old single-pass authoring option was retired: adaptive-script-author.js
 // is no longer reachable from the application, so asserting on a
 // "singlePass:true" call site inside workbench-workflow.js tests dead code.
 // The live guarantee is that the first-pass author module no longer routes
 // non-commerce writing through the retired adaptive author.
 const firstPass=fs.readFileSync(require.resolve('../app/first-pass-script-author'),'utf8');
 assert.match(firstPass,/buildFirstPassMessages/);
 const workflowSource=source;
 assert.doesNotMatch(workflowSource,/adaptive-script-author/);});
