'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),director=require('../app/film-continuity-director');
function fixture(){return {script:{raw:'甲把水壶放在桌上；下一镜与乙交谈。'},characters:[{id:'C01',name:'甲'}],shots:[{id:'S01',sceneId:'SC01',action:'Put the pitcher on the table.'},{id:'S02',sceneId:'SC01',action:'Continue speaking at the same table.'}],assetLibraries:{props:[{id:'P01',name:'pitcher'}]},scenes:[]};}
function result(){return {shots:['S01','S02'].map(shotId=>({shotId,openingEn:shotId==='S01'?'C01 holds P01.':'P01 remains on the table.',transitionsEn:shotId==='S01'?'C01 lowers P01, contacts the table and releases it.':'P01 stays in place while the characters speak.',endingEn:'P01 rests upright on the table.',visiblePropIds:['P01'],offscreenEn:'None',actions:[]}))};}
test('one source-bound global ledger survives resume, output timing changes and does not mutate source',async()=>{let p=fixture(),calls=0;const original=p.script.raw;const options={getProject:()=>p,saveProject:x=>p=x,generate:async()=>{calls++;return result();}};await director.plan(options);p.shots[0].duration=12;await director.plan(options);assert.equal(calls,1);assert.equal(p.script.raw,original);p.shots[1].action+=' C01 retrieves the pitcher.';await director.plan(options);assert.equal(calls,2);});
test('missing, duplicated, reordered or invented asset rows cannot masquerade as whole-film coverage',()=>{const p=fixture();for(const alter of [r=>r.shots.pop(),r=>r.shots.reverse(),r=>r.shots[1].shotId='S01',r=>r.shots[1].visiblePropIds.push('UNKNOWN')]){const r=result();alter(r);assert.throws(()=>director.validate(p,r));}});
test('source changes during planning retain the new source and reject stale output',async()=>{let p=fixture();await assert.rejects(director.plan({getProject:()=>p,saveProject:()=>assert.fail('stale save'),generate:async()=>{p.script.raw='New script';return result();}}),{code:'AGENT_SOURCE_CHANGED'});assert.equal(p.script.raw,'New script');});
test('quote IDs restore exact original text with one shared transport catalog',async()=>{let p=fixture();p.shots[0].dialogueTurns=[{sourceDialogueId:'D1',speakerId:'C01',text:'来了。'}];p.shots[1].dialogueTurns=[{sourceDialogueId:'D2',speakerId:'C01',text:'坐吧。'}];await director.plan({getProject:()=>p,saveProject:x=>p=x,generate:async(messages,options)=>{const input=JSON.parse(messages[1].content),row=options.responseSchema.properties.shots.items;assert.deepEqual(row.properties.actions.items.properties.speechConstraints.items.properties.dialogueId.enum,['D1','D2']);const r=result();r.shots[0].actions=[{id:'place',descriptionEn:'Place the pitcher on the table.',sourceQuoteId:input.sourceCatalog[0].id,speechConstraints:[{dialogueId:'D1',relation:'before'}]}];return r;}});assert.equal(p.filmContinuityPlan.result.shots[0].actions[0].sourceQuote,p.script.raw);});
test('clean-frame policy allows authored physical writing but still requires the actual overlay boundary',()=>{const c=require('../app/clean-frame-contract');assert.equal(c.hasLock(c.LOCK),true);assert.equal(c.hasLock(c.LOCK.slice(0,-1)+'; preserve original physical packaging and its printing.'),true);assert.equal(c.hasLock('Permit signatures anywhere and add titles.'),false);assert.equal(c.hasLock('Only photographed story-world content and no generated writing or graphic overlay'),true);});
test('one invalid continuity row is repaired without regenerating or losing a valid neighbor',async()=>{
 let p=fixture();const requested=[];await director.plan({getProject:()=>p,saveProject:v=>p=v,generate:async messages=>{const ids=JSON.parse(messages.at(-1).content).requestedShotIds;requested.push(ids);const r=result();if(requested.length===1)r.shots[1].visiblePropIds=['UNKNOWN'];else r.shots[0].endingEn='unwanted rewrite';return r;}});
 assert.deepEqual(requested,[['S01','S02'],['S02']]);assert.equal(p.filmContinuityPlan.result.shots[0].endingEn,'P01 rests upright on the table.');assert.deepEqual(p.filmContinuityPlan.result.shots[1].visiblePropIds,['P01']);
});
