const test=require('node:test'),assert=require('node:assert/strict');const {parseStructuredJson}=require('../app/ai-provider');const {normalizeCameraHeaders,sourceFor}=require('../app/h3-final-prompt-editor');
test('one surplus screenplay closer is locally repaired without adding or rewriting any content',()=>{const raw='{"commerceProfile":{},"plan":{"title":"保留原句","cast":[],"locations":[]},"scenes":[{"id":"S01"}]},"parts":[{"sceneId":"S01","scriptText":"他说原话 }} 不变","endState":"保留"}]}';const r=parseStructuredJson(raw,{requiredKeys:['plan','parts','commerceProfile']});assert.equal(r.plan.scenes[0].id,'S01');assert.equal(r.parts[0].scriptText,'他说原话 }} 不变');});
test('missing or ambiguous screenplay content cannot be manufactured by bracket recovery',()=>{for(const raw of ['{"plan":{},"parts":[],"commerceProfile":{}}broken','{"plan":{"scenes":[{"id":"S01"}]},"parts":[],"commerceProfile":{}}','{"plan":{"scenes":01}},"parts":[],"commerceProfile":{}}']){assert.equal(require('../app/structured-firstpass-json').recover(raw),null);}});
test('header canonicalization preserves all exact speech and meaningful timings',()=>{const s='[Shot 1] From 0 to 4 seconds. <d>[Chinese] 原话 [Shot 2] At 00:01.000. 不得改</d> [Shot 2] At 00:04.000. From 4 to 10 seconds.';const r=normalizeCameraHeaders(s);assert.ok(r.includes('\n[Shot 2] At 00:04.000, From 4 to 10 seconds.'));assert.equal(r.match(/<d>[\s\S]*?<\/d>/)[0],s.match(/<d>[\s\S]*?<\/d>/)[0]);});
test('speaker slots are supplied before final prompt authoring, and never reset at cuts',()=>{const r=sourceFor({id:'S1',duration:10,dialogueTurns:[{speakerId:'C08',text:'原话',onScreen:true,start:1,end:2},{speakerId:'C01',text:'回应',onScreen:true,start:3,end:4},{speakerId:'C08',text:'再次回应',onScreen:true,start:5,end:6}]});assert.deepEqual(r.dialogue.map(t=>t.speakerPrefix),['C08 (S1)','C01 (S2)','C08 (S1)']);});
test('invalid final prompt and still results retain targeted feedback beyond old limits until user cancellation',async()=>{const h3=require('../app/h3-final-prompt-editor');let p={shots:[{id:'S1',duration:10,providerSemanticCompileSource:'ai-batch',dialogueTurns:[]}]},n=0;await assert.rejects(h3.author({getProject:()=>p,saveProject:v=>p=v,settings:{textProvider:{}},projectId:'x',optionsFor:(_,__,o)=>o,generate:async()=>{if(++n>5)throw Object.assign(Error('cancelled'),{code:'PROVIDER_REQUEST_ABORTED'});return {items:[]}}}),{code:'PROVIDER_REQUEST_ABORTED'});assert.equal(n,6);n=0;const still=require('../app/storyboard-still-author');p={shots:[{id:'S1',duration:10,dialogueTurns:[],finalPromptEditing:{status:'authored',detailedDescriptionEn:'C01 stays present.'}}]};await assert.rejects(still.author({getProject:()=>p,saveProject:v=>p=v,kind:'frames',generate:async()=>{if(++n>5)throw Object.assign(Error('cancelled'),{code:'PROVIDER_REQUEST_ABORTED'});return {items:[]}}}),{code:'PROVIDER_REQUEST_ABORTED'});assert.equal(n,6);});
test('review source IDs bind exact performed lines and preserve negative findings',()=>{const c=require('../app/script-review-citations'),rows=c.catalog([{sceneId:'S01',scriptText:'母亲（对女儿；温和）：这是原话。\n女儿（对母亲；认真）：我听见了。'}]);const r=c.bind({ok:false,issues:[{message:'真实问题'}],editorial:{anchors:{need:{quoteId:'S01:L1'},cta:{quoteId:'bogus',quote:'假引文'}}}},rows);assert.equal(r.ok,false);assert.equal(r.issues[0].message,'真实问题');assert.equal(r.editorial.anchors.need.quote,rows[0].text);assert.equal(r.editorial.anchors.cta.quote,'');});
test('missing language markers are repaired locally only for exact source speech in exact order',()=>{const h=require('../app/h3-final-prompt-editor'),shot={dialogueTurns:[{text:'原话一'},{text:'原话二'}]};assert.equal(h.normalizeDialogueMarkers('<d>原话一</d> <d>原话二</d>',shot),'<d>[Chinese] 原话一</d> <d>[Chinese] 原话二</d>');for(const raw of ['<d>原话二</d> <d>原话一</d>','<d>增加台词</d> <d>原话二</d>','<d>原话一</d>'])assert.equal(h.normalizeDialogueMarkers(raw,shot),raw);});

test('review quotation tolerates formatting whitespace only, never missing or reordered content',()=>{const c=require('../app/script-review-citations');assert.equal(c.containsQuote('第一句。\n第二句。','第一句。第二句。'),true);assert.equal(c.containsQuote('第一句。中间句。第二句。','第一句。第二句。'),false);assert.equal(c.containsQuote('第一句。第二句。','第二句。第一句。'),false);});

test('name-supported capacity is not confused with following descriptive characters',()=>{const p=require('../app/commerce-authoring-policy'),product={name:'500毫升保温杯'};assert.deepEqual(p.validateProfile({sellingPoints:[{text:'500毫升容量便于日常装水',basis:'name',evidence:'500毫升'}]},product),[]);assert.ok(p.validateProfile({sellingPoints:[{text:'保温12小时',basis:'category_use',evidence:'保温杯'}]},product).length);});
