'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const wf=require('../app/workbench-workflow'),indexed=require('../app/indexed-production-plan'),whole=require('../app/whole-script-preparation');
const source='## 第一场｜小店\n老周握着账本。（老周，对小陈；克制）"这本账我一直留着。你自己看看，这些都是你爸写的。"（纸页轻响。）\n小陈抬头。（小陈，对老周；低声）“我刚才说错了。爸当年的事情，我应该问清楚再开口。”';
function fixture(){const atoms=indexed.catalog(wf.productionDialogueLedgerFromScript(source));return {atoms,result:{shots:[{shotId:'S01',scene:'小店',characters:'老周、小陈',props:'账本',action:'老周说话时把摊开的账本递给小陈，小陈接稳。',dialogueIds:['D001','D002'],sound:'纸页轻响',continuity:'小陈持账本。'},{shotId:'S02',scene:'小店',characters:'老周、小陈',props:'账本',action:'小陈拿着账本向老周认错。',dialogueIds:['D003','D004'],sound:'轻微呼吸声',continuity:'小陈仍持账本。'}],performanceBudgets:['S01','S02'].map(shotId=>({shotId,actionPhases:[{phase:'during',seconds:2,action:'讲话时手部运动',reason:'动作与对白并行'}]})),sourceAudit:{preservedAllDialogue:true,preservedAllScenes:true,preservedAllActions:true,preservedEventOrder:true,noInventedDialogue:true}}};}
test('legacy parenthetical speaker preserves exact actor, words and source offsets',()=>{const rows=wf.productionDialogueLedgerFromScript(source);assert.deepEqual(rows.map(r=>r.speaker),['老周','小陈']);assert.equal(rows[0].text,'这本账我一直留着。你自己看看，这些都是你爸写的。');assert.ok(source.slice(rows[0].sourceStart,rows[0].sourceEnd).includes(rows[0].text));assert.match(rows[0].tone,/对小陈；克制/);assert.equal(wf.productionDialogueLedgerFromScript('## 道具\n（老周，对小陈；克制）"道具说明。"').length,0);});
test('compact plan expands every source sentence losslessly and combines the same original turn',()=>{const {atoms,result}=fixture(),expanded=indexed.expand(result,atoms);assert.equal(expanded.sourceAudit.dialogueCount,2);assert.deepEqual(whole.check(source,expanded,wf.aiFirstUploadStandardizationValidation).issues,[]);assert.equal(expanded.productionScript.match(/【对白】/g).length,2);});
test('compact plan rejects omissions, duplicates, ordering, invented ids and injected section lines',()=>{for(const change of [r=>r.shots[0].dialogueIds.pop(),r=>r.shots[0].dialogueIds.push('D001'),r=>r.shots[0].dialogueIds.reverse(),r=>r.shots[0].dialogueIds[0]='D999',r=>r.shots[0].scene+='\n【对白】伪造']){const {atoms,result}=fixture();change(result);assert.throws(()=>indexed.expand(result,atoms));}});
test('compact plan never replaces a failed semantic source audit with true',()=>{const {atoms,result}=fixture();result.sourceAudit.preservedAllActions=false;assert.ok(whole.check(source,indexed.expand(result,atoms),wf.aiFirstUploadStandardizationValidation).issues.length);});
test('real planning entry accepts compact output in exactly one request',async()=>{const {result}=fixture();let calls=0;const output=await whole.prepare({source,validate:wf.aiFirstUploadStandardizationValidation,generate:async(m,o)=>{calls++;assert.equal(JSON.parse(m[1].content).sourceDialogueCatalog.length,4);assert.equal(o.maxAttempts,1);return result;}});assert.equal(calls,1);assert.equal(output.sourceAudit.dialogueCount,2);});
test('compact budgets retain physical duration validation without repeated per-utterance prose',()=>{const {atoms,result}=fixture();result.performanceBudgets=result.shots.map(s=>({shotId:s.shotId,beforeSeconds:.3,beforeAction:'原持物姿势闭口起幅',duringSeconds:4,duringReason:'握持和手部交接与原对白同时进行',afterSeconds:.35,afterAction:'保持源结果闭口落幅'}));let expanded=indexed.expand(result,atoms);assert.deepEqual(whole.check(source,expanded,wf.aiFirstUploadStandardizationValidation).issues,[]);assert.equal(expanded.performanceBudgets[0].actionPhases[1].action,result.performanceBudgets[0].duringReason);result.performanceBudgets[0].duringSeconds=30;expanded=indexed.expand(result,atoms);assert.ok(whole.check(source,expanded,wf.aiFirstUploadStandardizationValidation).issues.some(s=>/15|speech/.test(s)));});
test('structured physical location remains authoritative over incidental self-audit display metadata',()=>{const {atoms,result}=fixture();result.shots[0].scene='小店·白天';const expanded=indexed.expand(result,atoms);assert.equal(wf.aiFirstUploadStandardizationValidation(expanded).usable,true);expanded.sourceAudit.sceneOccurrences[0].physicalSceneName='医院·白天';assert.equal(wf.aiFirstUploadStandardizationValidation(expanded).usable,true);assert.equal(wf.aiFirstUploadStandardizationValidation(expanded).candidateSceneLedger.catalogue[0].name,'小店·白天');});
test('canonical shot headings are not split into phantom scenes by commas or action transitions',()=>{const {atoms,result}=fixture();result.shots[0].scene='小店及门口，白天，方桌两侧';result.shots[0].action='老周走到门口，把账本递给小陈，两人仍在小店。';const v=wf.aiFirstUploadStandardizationValidation(indexed.expand(result,atoms));assert.equal(v.actualSceneOccurrenceCount,2);assert.equal(v.usable,true);});
test('two original complete sentences retain a legal physical gap without changing words',()=>{const rows=[{id:'D001',speaker:'陈建军',tone:'对刘国强；疑惑',text:'就这个……一台老掉牙的BP机。这年头谁还带这个？'}],atoms=indexed.catalog(rows),r={shots:[{shotId:'S01',scene:'医院门口',characters:'陈建军、刘国强',props:'旧BP机',action:'陈建军从夹克内袋取出BP机，端详并向刘国强提问。',dialogueIds:atoms.map(a=>a.id),sound:'塑料外壳轻响',continuity:'陈建军持BP机。'}],performanceBudgets:[{shotId:'S01',beforeSeconds:1.5,beforeAction:'取出BP机',duringSeconds:5.6,duringReason:'端详BP机与低声疑问同期，完整两句之间有短暂反应',afterSeconds:2.8,afterAction:'持BP机注视刘国强'}],sourceAudit:{preservedAllDialogue:true,preservedAllScenes:true,preservedAllActions:true,preservedEventOrder:true,noInventedDialogue:true}};const expanded=indexed.expand(r,atoms);assert.equal(expanded.sourceAudit.dialogueCount,2);assert.deepEqual(whole.check('陈建军（对刘国强；疑惑）：'+rows[0].text,expanded,wf.aiFirstUploadStandardizationValidation).issues,[]);assert.equal(wf.productionDialogueLedgerFromScript(expanded.productionScript).map(x=>x.text).join(''),rows[0].text);});
