'use strict';
require('node:test')('canonical action quotes are performance directions, never extra speakers',()=>{const assert=require('node:assert/strict'),wf=require('../app/workbench-workflow');const s='### S01｜场景：小店\n【人物】李婷\n【动作】李婷快速：“怕你累着”，音高：“一直”，拿起围裙。\n【对白】李婷（对母亲；惭愧）：妈，是我说错了，往后这店里一直有你的位置。\n【声音】衣料摩擦。\n【承接】围裙挂稳。';assert.deepEqual(wf.productionDialogueLedgerFromScript(s).map(r=>r.speaker),['李婷']);});
const test=require('node:test'),assert=require('node:assert/strict');
const whole=require('../app/whole-script-preparation'),{aiFirstUploadStandardizationValidation:validate}=require('../app/workbench-workflow');
const {silenceFailures}=require('../app/shot-performance-contract'),{Budget,CODE}=require('../app/preproduction-budget');
const performance=require('../app/preproduction-performance'),writer=require('../app/adaptive-script-author'),commerce=require('../app/commerce-editorial-contract');
function fixture(){const lines=['甲（对乙；坚定）：这二十年的还款单我一直留着，我想要的是家人记得这份付出。','乙（对甲；愧疚）：爸，是我刚才说错了，这个家一直有您的位置，快进来坐下。'];const source=lines.join('\n');const result={productionScript:lines.map((line,i)=>`### S0${i+1}｜场景：家\n【人物】甲、乙\n【核心物品】还款单\n【动作】说话时递交原还款单，听者垂下目光。\n【对白】${line}\n【声音】纸页摩擦声\n【承接】乙持还款单。`).join('\n'),performanceBudgets:lines.map((_,i)=>({shotId:`S0${i+1}`,actionPhases:[{phase:'before',action:'握稳原凭据',seconds:.3,reason:'闭口准备'},{phase:'during',action:'说话同时将原凭据递给听者',seconds:2,reason:'同一时间的手部交接，不增加发声'},{phase:'after',action:'听者低头看原凭据',seconds:.35,reason:'结果落点'}]})),sourceAudit:{sceneOccurrenceCount:2,dialogueCount:2,sceneOccurrences:[{order:1,physicalSceneName:'家'},{order:2,physicalSceneName:'家'}],preservedAllDialogue:true,preservedAllScenes:true,preservedAllActions:true,preservedEventOrder:true,noInventedDialogue:true}};return {source,result};}
test('whole screenplay succeeds in one model request, preserves all speech and reuses exact checkpoint',async()=>{const {source,result}=fixture();let calls=0,checkpoint;const output=await whole.prepare({source,validate,generate:async(m,o)=>{calls++;assert.equal(o.stage,'uploaded_script_prepare_whole');assert.equal(JSON.parse(m[1].content).completeSource,source);return result;},save:v=>checkpoint=structuredClone(v)});assert.equal(calls,1);assert.equal(output.sourceAudit.dialogueCount,2);assert.equal(checkpoint.parts.length,1);await whole.prepare({source,validate,checkpoint,generate:()=>{throw Error('completed result must be reused');}});});
test('whole screenplay rejects removed, changed, reordered and wrong-speaker dialogue',()=>{const {source,result}=fixture();for(const productionScript of [result.productionScript.replace('家人记得','孩子忘掉'),result.productionScript.replace('【对白】乙','【对白】甲'),result.productionScript.split('### S02')[0]])assert.ok(whole.check(source,{...result,productionScript},validate).issues.some(x=>/dialogue|coverage/.test(x)));});
test('pacing advice cannot block an otherwise complete source-grounded plan',async()=>{let n=0;const f=fixture();const r=await whole.prepare({source:f.source,validate,generate:async()=>{n++;return {...f.result,sourceTimingIssues:[{exactSourceExcerpt:'他大口咀嚼后咽下。',conflict:'5 seconds without speech'}]};}});assert.ok(r.productionScript);assert.equal(n,1);});
test('3-second editorial advisory checks leading, interline and trailing gaps including off-screen speech',()=>{assert.deepEqual(silenceFailures([{start:3,end:7}],10),[]);for(const turns of [[{start:3.02,end:8}],[{start:.3,end:6.98}],[{start:.3,end:2},{start:5.02,end:9.65}],[]])assert.ok(require("../app/shot-performance-contract").silenceAdvisories(turns,10).length);assert.deepEqual(silenceFailures([{start:1,end:5,onScreen:false},{start:6,end:9}],10),[]);});
test('format repair moves generated acting into cue without changing spoken words',()=>{const source={scriptText:'老宋稳稳托着罐子（对观众；诚恳）：三十九点九元一罐。'};const fixed=writer.canonicalizeGeneratedSpeaker(source,['老宋']);assert.equal(fixed.scriptText,'老宋（对观众；诚恳；稳稳托着罐子）：三十九点九元一罐。');});
test('required opening hook cannot be omitted from a new story plan',async()=>{await assert.rejects(writer.author({topic:{},product:{},commerceMode:'none',requireOpeningHook:true,generate:async()=>({title:'故事',cast:[],locations:[],scenes:[{id:'A',trigger:'事',result:'果'}],ending:'和解'})}),/开场爆点/);});
test('timed commerce audit waits for actual dialogue windows without a remote request or false zero',async()=>{let calls=0;const r=await commerce.review({units:[{id:'S01',duration:10,text:'真实完整台词',turns:[{text:'真实完整台词'}]}],product:{},mode:'explicit',generate:()=>{calls++;}});assert.equal(r.status,'timing_pending');assert.equal(r.timing,null);assert.equal(calls,0);assert.equal(r.ok,false);});
test('execution profile never changes an explicitly chosen model or effort',()=>{const c={localAgent:{id:'codex',model:'chosen-model',reasoningEffort:'high',speed:'standard'}};assert.equal(performance.executionConfig(c,{latencyProfile:performance.VERSION}).localAgent.reasoningEffort,'high');assert.equal(performance.executionConfig({localAgent:{id:'codex',model:'chosen-model'}},{latencyProfile:performance.VERSION}).localAgent.model,'chosen-model');assert.equal(performance.executionConfig({localAgent:{id:'codex'}},{latencyProfile:performance.VERSION}).localAgent.reasoningEffort,undefined);});
test('text budget counts overlapping work once and excludes human idle time',async()=>{let now=0,p={id:'P'};const b=new Budget({getProject:()=>structuredClone(p),saveProject:v=>p=v},{now:()=>now,limitMs:10000});const options={latencyProfile:performance.VERSION,costProjectId:'P',costOperation:'h3_final_editor'};let doneA,doneB;const a=b.run(options,()=>new Promise(r=>doneA=r));now=500;const c=b.run(options,()=>new Promise(r=>doneB=r));now=2000;doneA(1);await a;now=3000;doneB(2);await c;assert.equal(p.preproductionTiming.elapsedMs,3000);now=100000;await b.run(options,async()=>{now+=1000;});assert.equal(p.preproductionTiming.elapsedMs,4000);});
test('legacy text budget cannot abort production after elapsed time',async()=>{let p={id:'P'},now=0;const b=new Budget({getProject:()=>structuredClone(p),saveProject:v=>p=v},{now:()=>now,limitMs:25});const result=await b.run({latencyProfile:performance.VERSION,costProjectId:'P',costOperation:'topics'},async()=>{now=9000000;return 'complete';});assert.equal(result,'complete');assert.equal(p.preproductionTiming.exceeded,false);assert.equal(p.preproductionTiming.limitMs,0);});
