'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createProductDraftStore}=require('../app/renderer/product-draft-store');
function setup(save) {const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const store=createProductDraftStore({storage,save,delay:60000,retryDelay:60000});return{store,storage,data};}
const reply=(id,product,at='2026-09-15T04:00:01Z')=>({ok:true,project:{id,product,updatedAt:at}});
test('all commodity fields persist, preserve image and survive reload',async()=>{let product={imagePath:'original.png'};const x=setup(async(id,patch)=>reply(id,product={...product,...patch.product}));for(const [k,v] of Object.entries({name:'玫台黄精五黑膏',price:'真实测试价',sellingPoints:'日常食品',offer:'活动说明',purchaseInstructions:'进入橱窗'}))x.store.edit('a',k,v);const next=createProductDraftStore({storage:x.storage,save:async(id,p)=>reply(id,product={...product,...p.product}),delay:60000});assert.equal(next.apply({id:'a',product:{}}).product.price,'真实测试价');await x.store.flush('a');await next.flush('a');assert.equal(product.imagePath,'original.png');assert.equal(product.description,'日常食品');assert.equal(x.data.size,0);});
test('delayed first save cannot erase edits typed while pending',async()=>{let release,calls=[];const x=setup(async(id,p)=>{calls.push(p.product);if(calls.length===1)await new Promise(r=>release=r);return reply(id,p.product);});x.store.edit('a','price','19');const pending=x.store.flush('a');x.store.edit('a','price','29.9');assert.equal(x.store.apply({id:'a',product:{price:''}}).product.price,'29.9');release();await pending;assert.deepEqual(calls.map(p=>p.price),['19','29.9']);assert.equal(x.store.apply({id:'a',updatedAt:'2026-09-15T04:00:00Z',product:{price:''}}).product.price,'29.9');});
test('project switches cannot redirect draft or completion',async()=>{let calls=[];const x=setup(async(id,p)=>{calls.push(id);return reply(id,p.product);});x.store.edit('a','name','甲商品');x.store.edit('b','name','乙商品');await Promise.all([x.store.flush('a'),x.store.flush('b')]);assert.deepEqual(calls.sort(),['a','b']);assert.equal(x.store.apply({id:'c',product:{name:'丙商品'}}).product.name,'丙商品');});
test('failed write retains journal and a retry saves the same input',async()=>{let fail=true;const x=setup(async(id,p)=>fail?{ok:false,message:'offline'}:reply(id,p.product));x.store.edit('a','price','39.9');await assert.rejects(x.store.flush('a'));assert.equal(JSON.parse([...x.data.values()][0]).price,'39.9');fail=false;await x.store.flush('a');assert.equal(x.data.size,0);});
test('clearing a field is persisted and does not restore a legacy price',async()=>{const x=setup(async(id,p)=>reply(id,p.product));x.store.edit('a','price','');await x.store.flush('a');assert.equal(x.store.apply({id:'a',product:{price:'old',salePrice:'old'}}).product.price,'');});
