'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const review=require('../app/screenplay-review-partitions'),writer=require('../app/shot-screenplay');
function input(){const d=require('./shot-screenplay-fixture').fixture();d.format='compact-screenplay-v2';d.shots=Array.from({length:12},(_,i)=>({...structuredClone(d.shots[0]),id:'S'+(i+1),action:'相视交谈。'}));return {mode:'upload',screenplay:d,originalSource:'immutable complete source',product:{name:'test'},productClaimAuthority:require('../app/product-claim-authority').packet({name:'test'})};}
function result(m){const p=JSON.parse(m[1].content);if(p.reviewScope.kind==='whole-film-semantics')return {ok:true,storyComplete:true,sourcePreserved:true,criteria:Object.fromEntries(['story','commerce','dialogue'].map(k=>[k,{passed:true,evidence:'complete film fixture '+k}])),issues:[]};return {ok:true,checks:Object.fromEntries(p.reviewScope.targetShotIds.map(id=>[id,{evidence:'source clip performance '+id}])),issues:[]};}
test('full semantic review and every local shot are required; negative local verdict cannot become a pass',async()=>{
 const i=input(),calls=[];const audit=await review.review({input:i,reviewRules:writer.REVIEW_RULES,state:{},save:()=>{},signature:'test',generate:async(m)=>{const p=JSON.parse(m[1].content);calls.push(p);const r=result(m);if(p.reviewScope.kind==='local-performance'&&p.reviewScope.targetShotIds?.includes('S6')){r.ok=false;r.issues=[{shotIds:['S6'],field:'duration',evidence:'source clip not feasible',repair:'regroup complete neighboring lines'}];}return r;}});
 assert.equal(audit.ok,false);assert.equal(audit.issues.length,1);assert.equal(Object.keys(audit.checks).length,12);assert.equal(calls.length,4);
 assert.equal(calls.filter(p=>p.originalSource).length,1);assert.equal(calls.find(p=>p.originalSource).screenplay.shots.length,12);
 assert.deepEqual(calls.find(p=>p.reviewScope.kind==='local-performance'&&p.reviewScope.targetShotIds?.includes('S6')).reviewScope.before.id,'S5');
});
test('cancellation keeps completed receipts and stable running request identity; resume changes only affected groups',async()=>{
 const i=input(),state={},calls=[];let fail=true;
 const generate=async(m,o)=>{const p=JSON.parse(m[1].content),key=p.reviewScope.kind==='whole-film-semantics'?'film':p.reviewScope.kind==='whole-film-causal-evidence'?'causal':p.reviewScope.targetShotIds[0];calls.push({key,session:o.sessionId});if(fail&&key==='S6')throw Object.assign(Error('test cancellation'),{code:'PROVIDER_REQUEST_ABORTED'});return result(m);};
 const args={input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'resume',generate,concurrency:1};await assert.rejects(review.review(args),/test cancellation/);assert.equal(state.reviewPartitions.entries.film.status,'completed');fail=false;const r=await review.review(args);assert.equal(r.ok,true);assert.equal(calls.filter(c=>c.key==='film').length,1);assert.equal(calls.filter(c=>c.key==='S1').length,1);assert.equal(calls.filter(c=>c.key==='S6')[0].session,calls.filter(c=>c.key==='S6')[1].session);
 calls.length=0;i.screenplay.shots[7].ending='changed source';await review.review(args);assert.deepEqual(calls.map(c=>c.key).sort(),['S6','film']);
});
test('malformed negative receipt is repaired only within its group and never silently approved',async()=>{
 const i=input(),state={};let repairs=0,filmCalls=0;await review.review({input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'invalid',generate:async(m)=>{const p=JSON.parse(m[1].content),r=result(m);if(p.reviewScope.kind==='whole-film-semantics')filmCalls++;if(p.reviewScope.targetShotIds?.[0]==='S6'&&repairs++===0)return {...r,ok:false,issues:[]};return r;}});assert.equal(repairs,2);assert.equal(filmCalls,1);assert.equal(state.reviewPartitions.entries['shots-S6-S7-S8-S9-S10'].attempt,1);
});
test('administrative summary and unrelated identities do not invalidate local reviews; referenced identities do',async()=>{
 const i=input(),state={},calls=[];i.screenplay.characters.push({id:'UNUSED',name:'unrelated character',description:'before'});const args={input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'scoped-assets',generate:async(m)=>{const p=JSON.parse(m[1].content);calls.push(p);return result(m);}};
 await review.review(args);calls.length=0;i.screenplay.story.synopsis+='\nAdministrative standardization note.';i.screenplay.characters.at(-1).description='after';await review.review(args);assert.equal(calls.length,1);assert.equal(calls[0].reviewScope.kind,'whole-film-semantics');
 calls.length=0;i.screenplay.characters[0].voiceDescription='changed fixed identity';await review.review(args);assert.equal(calls.length,4);for(const c of calls.filter(c=>c.reviewScope.kind==='local-performance')){assert.equal(c.screenplay.story,undefined);assert.ok(!c.screenplay.characters.some(c=>c.id==='UNUSED'));assert.ok(c.referenceIdentities.characters.some(c=>c.id==='UNUSED'));}
});
test('real compact author dispatches one complete writer then checkpointed review tasks for a long script',async()=>{
 const source=require('./shot-screenplay-fixture').fixture();const d={format:'compact-screenplay-v2',story:source.story,characters:source.characters.map(({id,name,description,assetRequired,role,voiceDescription})=>({id,name,description,assetRequired,role,voiceDescription})),scenes:source.scenes.map(({id,name,description,assetRequired})=>({id,name,description,assetRequired})),props:[],shots:Array.from({length:6},(_,i)=>{const {beats,transition,sound,wardrobeBindings,...s}=structuredClone(source.shots[0]);return {...s,id:'S'+(i+1),action:'人物交谈后相视。',dialogue:s.dialogue.map(({start,end,...line})=>({...line,id:'D'+(i+1)}))};})};
 let writes=0,reviews=0,saved;const r=await writer.author({topic:{title:'test'},save:s=>saved=structuredClone(s),generate:async(m,o)=>{if(o.stage==='shot_screenplay_write'){writes++;return d;}reviews++;return result(m);}});
 assert.equal(writes,1);assert.equal(reviews,3);assert.equal(r.status,'ready');assert.equal(r.document.shots.length,6);assert.equal(Object.values(saved.reviewPartitions.entries).filter(e=>e.status==='completed').length,3);
 saved.signature='prior-source-policy';const resumed=await writer.author({topic:{title:'test'},checkpoint:saved,generate:async()=>assert.fail('identical review inputs must reuse saved Agent receipts')});assert.equal(resumed.status,'ready');assert.equal(resumed.document.shots.length,6);
});

test('Agent advisories persist without discarding genuine issues or overriding a negative verdict',async()=>{
 const state={},i=input();let retry=0;const r=await review.review({input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'advisories',generate:async(m)=>{assert.ok(m[0].content.includes(require('../app/screenplay-source-authority').INSTRUCTION));const p=JSON.parse(m[1].content),v=result(m);if(p.reviewScope.kind==='whole-film-semantics'){v.advisories=[{evidence:'old administrative estimate differs',note:'Current real duration meets the unchanged user policy.'}];if(retry++===0)return {...v,ok:false};}if(p.reviewScope.kind==='local-performance'&&p.reviewScope.targetShotIds?.includes('S6'))return {...v,ok:false,issues:[{shotIds:['S6'],field:'holder',evidence:'two incompatible current holders',repair:'Repair the causal handover in the source.'}]};return v;}});
 assert.equal(retry,2);assert.equal(r.ok,false);assert.equal(r.advisories.length,1);assert.equal(r.issues.length,1);assert.equal(r.issues[0].field,'holder');assert.equal(state.reviewPartitions.entries.film.result.advisories[0].evidence,'old administrative estimate differs');
});
test('writer and every real review partition inherit the same source conflict authority',()=>{
 const authority=require('../app/screenplay-source-authority').INSTRUCTION;assert.ok(writer.RULES.includes(authority));assert.ok(writer.REVIEW_RULES.includes(authority));const tasks=review.plan(input(),writer.REVIEW_RULES);for(const task of tasks)assert.ok(task.messages[0].content.includes(authority),task.key+' must retain user-authorized standardization and reject invented causality');
});
test('film causal evidence cannot be waived by positive local reviews',async()=>{
 const i=input(),state={},before=structuredClone(i.screenplay);const audit=await review.review({input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'causal-gate',generate:async(m)=>{const p=JSON.parse(m[1].content),r=result(m);if(p.reviewScope.kind==='whole-film-semantics'){assert.equal(p.screenplay.shots.length,12);assert.equal(p.originalSource,i.originalSource);return {...r,ok:false,issues:[{shotIds:['S2','S11'],field:'retrospective object identity',evidence:'S2 affects object B; S11 says object A was affected',repair:'Agent chooses the minimal source correction while retaining the reveal.'}]};}return r;}});
 assert.equal(audit.ok,false);assert.equal(audit.issues.length,1);assert.deepEqual(audit.issues[0].shotIds,['S2','S11']);assert.equal(state.reviewPartitions.entries.film.result.ok,false);assert.deepEqual(i.screenplay,before);assert.ok(audit.reviewParts.some(r=>r.scope==='film'&&!r.result.ok));
});
test('adding causal coverage reuses every unchanged previously completed review receipt',async()=>{
 const i=input(),state={},args={input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'coverage-upgrade',generate:async m=>result(m)};await review.review(args);state.reviewPartitions.entries.causal={status:'completed',result:{ok:false}};let calls=0;const r=await review.review({...args,generate:async m=>{calls++;return result(m);}});assert.equal(calls,0);assert.equal(r.ok,true);assert.ok(!r.reviewParts.some(p=>p.scope==='causal'));
});

test('history-only hints cannot invalidate current evidence or rewrite receipt provenance',async()=>{const i=input(),state={},calls=[],args={input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'evidence-cache',generate:async m=>{calls.push(JSON.parse(m[1].content).reviewScope.kind);return result(m);}};i.previousReview={issues:[{shotIds:['S1'],field:'old clue',evidence:'historical only',repair:'already completed'}]};await review.review(args);const oldHash=state.reviewPartitions.entries['shots-S1-S2-S3-S4-S5'].requestHash;calls.length=0;i.previousReview={issues:[]};i.changedShotIds=['S10'];i.reviewDeliveryIssues=['old request metadata'];await review.review(args);assert.deepEqual(calls,[]);assert.equal(state.reviewPartitions.entries['shots-S1-S2-S3-S4-S5'].requestHash,oldHash);i.downstreamReviewFeedback={requirement:'current genuine review feedback'};await review.review(args);assert.ok(calls.includes('local-performance'));});
test('legacy receipts require exact provenance before acquiring an evidence key',async()=>{const i=input(),state={},args={input:i,reviewRules:writer.REVIEW_RULES,state,save:()=>{},signature:'legacy-cache',generate:async m=>result(m)};await review.review(args);for(const e of Object.values(state.reviewPartitions.entries))delete e.evidenceHash;let calls=0;await review.review({...args,generate:async m=>{calls++;return result(m);}});assert.equal(calls,0);assert.ok(state.reviewPartitions.entries.film.evidenceHash);delete state.reviewPartitions.entries.film.evidenceHash;state.reviewPartitions.entries.film.requestHash='different-legacy-full-request';i.previousReview={issues:[{shotIds:['S1'],field:'new historical hint',evidence:'hint',repair:'hint'}]};await review.review({...args,generate:async m=>{calls++;return result(m);}});assert.equal(calls,1);});
test('real source, neighboring state, requirements and schema remain evidence dependencies',()=>{const i=input(),tasks=review.plan(i,writer.REVIEW_RULES),local=tasks.find(t=>t.kind==='local'),key=review.evidenceFingerprint(local);for(const edit of [t=>t.messages[0].content+=' current requirement',t=>t.schema.properties.current={type:'boolean'},t=>{const p=JSON.parse(t.messages[1].content);p.reviewScope.after.ending='different state';t.messages[1].content=JSON.stringify(p);},t=>{const p=JSON.parse(t.messages[1].content);p.screenplay.shots[0].action='new action';t.messages[1].content=JSON.stringify(p);}]){const t=structuredClone(local);edit(t);assert.notEqual(review.evidenceFingerprint(t),key);}});

test('every source review task inherits common evidence scope and film owns causality',()=>{const scope=require('../app/screenplay-review-evidence-scope');for(const t of review.plan(input(),writer.REVIEW_RULES)){assert.ok(t.messages[0].content.includes(scope.INSTRUCTION),t.key);assert.deepEqual(t.schema.properties.advisories,scope.ADVISORIES);}const film=review.plan(input(),writer.REVIEW_RULES).find(t=>t.kind==='film');assert.match(film.messages[0].content,/跨场因果/);});

test('actual source reviewer requests exclude stale verdicts while preserving real current feedback',()=>{const i=input();i.previousReview={issues:[{shotIds:['S1'],evidence:'stale missing prop claim'}]};i.historicalIssues=['old'];i.changedShotIds=['S1'];i.reviewDeliveryIssues=['old transport receipt'];i.downstreamReviewFeedback={userRule:'current requirement'};const before=structuredClone(i);for(const task of review.plan(i,writer.REVIEW_RULES)){const p=JSON.parse(task.messages[1].content);assert.equal(p.historicalIssues,undefined);assert.equal(p.previousReview,undefined);assert.equal(p.changedShotIds,undefined);assert.equal(p.reviewDeliveryIssues,undefined);if(task.kind!=='causal')assert.deepEqual(p.downstreamReviewFeedback,i.downstreamReviewFeedback);}assert.deepEqual(i,before);});
