'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const policy=require('../app/commerce-authoring-policy');
const product={name:'折叠雨伞',price:'39.9/一件',offer:'99.9/三件',purchaseInstructions:'进入商品橱窗查看',sellingPoints:'根据产品特性自由编辑'};
const inferred={text:'折叠收纳后便于日常随身携带',basis:'category_use',evidence:'折叠雨伞'};
test('the user writing entry finishes all text stages before returning',async()=>{const {WorkbenchWorkflow}=require('../app/workbench-workflow'),calls=[];const ctx={runTrackedOperation:async(id,op,target,run)=>run(),generateCompleteScript:async(id,opts)=>{assert.equal(opts.track,false);calls.push('write');},prepareWrittenScriptForConfirmation:async()=>{calls.push('prepare_and_confirm');return {id:'p'};}};await WorkbenchWorkflow.prototype.generateCompleteScript.call(ctx,'p');assert.deepEqual(calls,['write','prepare_and_confirm']);});
for(const mode of ['asset_direct','keyframe','continuation','smart','storyboard_sheet'])test('complete prompt delivery waits for confirmation in '+mode,async()=>{const {WorkbenchWorkflow}=require('../app/workbench-workflow'),calls=[];const p={id:'p',generation:{mode},script:{raw:'保留原稿'},shots:[]};const ctx={store:{getProject:()=>p},setAutomation:()=>{},analyzeScript:async()=>{calls.push('analysis');p.shots=[{id:'S01'}];},requestPromptReview:async(id,opts)=>{assert.equal(opts.continueAfterApproval,false);assert.equal(opts.allowCrossStage,false);assert.equal(opts.requestedAction,'script_prompt_delivery');p.promptReview={status:'ready',items:[{id:'prompt',prompt:'完整提示词'}]};calls.push('confirmation');return {project:p};}};assert.equal(await WorkbenchWorkflow.prototype.prepareWrittenScriptForConfirmation.call(ctx,'p'),p);assert.deepEqual(calls,['analysis','confirmation']);calls.length=0;await WorkbenchWorkflow.prototype.prepareWrittenScriptForConfirmation.call(ctx,'p');assert.deepEqual(calls,['confirmation']);assert.equal(p.script.raw,'保留原稿');p.shots[0].promptCompilationPending=true;await assert.rejects(WorkbenchWorkflow.prototype.prepareWrittenScriptForConfirmation.call(ctx,'p'),{code:'PROMPT_DELIVERY_INCOMPLETE'});});
test('structured lines make dialogue ownership and line boundaries deterministic',()=>{const {renderPart}=require('../app/screenplay-lines');const p={sceneId:'S01',lines:[{kind:'action',text:'母亲站在门口，女儿拿着书包。'},{kind:'dialogue',speaker:'母亲',listener:'女儿',delivery:'平静',action:'手持雨伞',text:'把伞放进包里吧。'},{kind:'dialogue',speaker:'女儿',listener:'母亲',delivery:'认真',action:'双手接稳雨伞',text:'我收好，明天陪你去。'}],endState:'女儿持伞'};const result=renderPart(p,[{name:'母亲'},{name:'女儿'}]);assert.equal(result.scriptText.split('\n').length,3);assert.match(result.scriptText,/\n母亲（对女儿/);assert.deepEqual(require('../app/adaptive-script-author').localSourceIssues([result],['母亲','女儿']),[]);assert.equal(p.scriptText,undefined);assert.match(renderPart({...p,lines:[{...p.lines[1],speaker:'电话里的老师'}]},[{name:'母亲'},{name:'女儿'}]).scriptText,/电话里的老师/);assert.throws(()=>renderPart({...p,lines:[{...p.lines[1],speaker:''}]},[{name:'母亲'},{name:'女儿'}]),{code:'SCRIPT_FIRST_PASS_INCOMPLETE'});});
function profile(text){return {category:'雨伞',referencePattern:'care_demonstration',sellingPoints:[inferred,{text,basis:'user',evidence:'交易条件'}],storyBridge:'母亲为女儿准备通勤用品'};}
test('exact supplied commercial terms normalize losslessly outside inferred selling points',()=>{const source=profile('价格与活动明确：39.9/一件，99.9/三件，进入商品橱窗查看'),before=structuredClone(source);const n=policy.normalizeProfile(source,product);assert.equal(n.changes.length,1);assert.deepEqual(n.profile.sellingPoints,[inferred]);assert.deepEqual(source,before);assert.deepEqual(policy.validateProfile(n.profile,product),[]);assert.equal(n.changes[0].original.text,before.sellingPoints[1].text);});
for(const text of ['价格与活动明确：19.9/一件，99.9/三件，进入商品橱窗查看','价格：39.9/一件，保证不漏雨','39.9/一件，限时仅剩三件','39.9/一件，99.9/三件，扫码转账','只要39.9/一件','39.9/一件免邮'])test('unsupported words are not silently dropped: '+text,()=>{const n=policy.normalizeProfile(profile(text),product);assert.equal(n.changes.length,0);assert.ok(policy.validateProfile(n.profile,product).length);});
test('explicit selling point that happens to be a commercial term stays exactly user authored',()=>{const p={...product,sellingPoints:'39.9/一件'};const n=policy.normalizeProfile(profile('39.9/一件'),p);assert.equal(n.changes.length,0);assert.deepEqual(policy.validateProfile(n.profile,p),[]);});
test('normalization cannot turn only commercial terms into a valid inferred profile',()=>{const p=profile('39.9/一件');p.sellingPoints.shift();assert.ok(policy.validateProfile(policy.normalizeProfile(p,product).profile,product).length);});
test('exact subline review quotes retain true order within one dialogue line',()=>{const c=require('../app/script-review-citations');const text='母亲：你需要随身带伞。这把折叠雨伞能收起来。';const r=c.bind({editorial:{anchors:{need:{quoteId:'S01:L1',quote:'你需要随身带伞。'},introduction:{quoteId:'S01:L1',quote:'这把折叠雨伞能收起来。'}}}},[{quoteId:'S01:L1',unitId:'S01',text}]);assert.equal(r.editorial.anchors.need.quote,'你需要随身带伞。');assert.ok(text.indexOf(r.editorial.anchors.need.quote)<text.indexOf(r.editorial.anchors.introduction.quote));const unknown=c.bind({openingCheck:{quoteId:'missing',quote:'invented'}},[]);assert.equal(unknown.openingCheck.quote,'');});
test('every production author gets stage-specific preflight and one attempt',()=>{for(const file of ['asset-design-author','h3-final-prompt-editor','storyboard-still-author','whole-script-preparation','first-pass-script-author']){const s=fs.readFileSync(require.resolve('../app/'+file),'utf8');if(file==='h3-final-prompt-editor'){assert.match(s,/final-prompt-blocks/);assert.match(s,/maxAttempts:1/);}else{assert.match(s,/first-delivery-contract/);assert.match(s,/maxAttempts:1/);}}});
test('cached format-only failure advances directly to review without a paid rewrite',async()=>{const {author}=require('../app/first-pass-script-author');let n=0;const topic={id:'test'},output={commerceProfile:profile('价格与活动明确：39.9/一件，99.9/三件，进入商品橱窗查看'),plan:{title:'伞',cast:[{name:'母亲'},{name:'女儿'}],locations:[{name:'门口'}],scenes:[{id:'S01'}]},parts:[{sceneId:'S01',scriptText:'母亲（对女儿；平静；手持雨伞）：把伞放进包里吧。',endState:'母亲持伞'}]};const checkpoint=await author({topic,product,commerceMode:'none',requireOpeningHook:false,generate:async()=>++n===1?output:{ok:false,issues:[{sceneId:'S01',message:'用户卖点引用必须与用户原资料完全一致'}],checks:[{}]}});checkpoint.commerceProfile=output.commerceProfile;checkpoint.repairRequest={id:'explicit-click'};const parts=structuredClone(checkpoint.parts),stages=[];const result=await author({topic,product,commerceMode:'none',checkpoint,requireOpeningHook:false,generate:async(m,o)=>{stages.push(o.stage);return {ok:true,issues:[],checks:[{}]};}});assert.deepEqual(stages,['adaptive_script_review_first_pass']);assert.deepEqual(result.parts,parts);assert.equal(result.explicitRepairCalls,undefined);});
