"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("dramaSlot", {
  localAgents: {
    call: (method, ...args) => ipcRenderer.invoke("local-agents:call", method, args)
  },
  appMode: {
    get: () => ipcRenderer.invoke("app-mode:get"),
    select: mode => ipcRenderer.invoke("app-mode:select", mode)
  },
  mcp: {
    getConnectionInfo: () => ipcRenderer.invoke("mcp:get-connection-info"),
    testConnection: () => ipcRenderer.invoke("mcp:test-connection"),
    copyConfig: format => ipcRenderer.invoke("mcp:copy-config", format)
  },
  simple: {
    call: (method, ...args) => ipcRenderer.invoke("simple:call", method, args),
    updateProduct: (projectId, product) => ipcRenderer.invoke("simple:call", "updateProduct", [projectId, product])
  },
  exportProjectLogs: (projectId, scope) => ipcRenderer.invoke("project:export-logs", projectId, scope),
  defaults: () => ipcRenderer.invoke("app:defaults"),
  checkUpdate: () => ipcRenderer.invoke("app:check-update"),
  installUpdate: () => ipcRenderer.invoke("app:install-update"),
  onUpdateStatus: callback => {
    const listener = (_event, state) => callback(state);
    ipcRenderer.on("app:update-status", listener);
    return () => ipcRenderer.removeListener("app:update-status", listener);
  },
  health: () => ipcRenderer.invoke("bridge:health"),
  diagnostics: () => ipcRenderer.invoke("bridge:diagnostics"),
  chooseMedia: (type, options = {}) => ipcRenderer.invoke("media:choose", { type, ...options }),
  chooseOutput: () => ipcRenderer.invoke("file:choose-output"),
  submit: payload => ipcRenderer.invoke("video:submit", payload),
  query: taskId => ipcRenderer.invoke("video:query", taskId),
  reveal: targetPath => ipcRenderer.invoke("file:reveal", targetPath),
  workbench: {
    listProjects: () => ipcRenderer.invoke("workbench:list-projects"),
    createProject: (title, options) => ipcRenderer.invoke("workbench:create-project", title, options),
    importProductionPackage: () => ipcRenderer.invoke("workbench:import-production-package"),
    deleteProject: projectId => ipcRenderer.invoke("workbench:delete-project", projectId),
    purgeProject: projectId => ipcRenderer.invoke("workbench:purge-project", projectId),
    listDeletedProjects: () => ipcRenderer.invoke("workbench:list-deleted-projects"),
    restoreProject: archiveId => ipcRenderer.invoke("workbench:restore-project", archiveId),
    getProject: projectId => ipcRenderer.invoke("workbench:get-project", projectId),
    patchProject: (projectId, patch) => ipcRenderer.invoke("workbench:patch-project", projectId, patch),
    getSettings: () => ipcRenderer.invoke("workbench:get-settings"),
    getStorageLocation: () => ipcRenderer.invoke("workbench:get-storage-location"),
    foundryStatus: () => ipcRenderer.invoke("workbench:foundry-status"),
    chooseStorageLocation: () => ipcRenderer.invoke("workbench:choose-storage-location"),
    saveSettings: settings => ipcRenderer.invoke("workbench:save-settings", settings),
    resetSettings: () => ipcRenderer.invoke("workbench:reset-settings"),
    authStatus: () => ipcRenderer.invoke("workbench:auth-status"),
    licenseStatus: () => ipcRenderer.invoke("license:status"),
    licenseActivate: code => ipcRenderer.invoke("license:activate", code),
    licenseLogout: () => ipcRenderer.invoke("license:logout"),
    walletStatus: () => ipcRenderer.invoke("license:wallet"),
    createRechargeOrder: amountYuan => ipcRenderer.invoke("license:payment-create", amountYuan),
    rechargeOrderStatus: orderNo => ipcRenderer.invoke("license:payment-status", orderNo),
    openTutorial: () => ipcRenderer.invoke("workbench:open-tutorial"),
    openExternal: url => ipcRenderer.invoke("shell:open-external", url),
    syncVideoJobs: options => ipcRenderer.invoke("workbench:sync-video-jobs", options || {}),
    testProvider: (kind, config) => ipcRenderer.invoke("workbench:test-provider", kind, config),
    listTextModels: config => ipcRenderer.invoke("workbench:list-text-models", config),
    chooseProduct: projectId => ipcRenderer.invoke("workbench:choose-product", projectId),
    importCandidate: (projectId, entityType, entityId, stage) => ipcRenderer.invoke("workbench:import-candidate", projectId, entityType, entityId, stage),
    importBatchMedia: (projectId, kind) => ipcRenderer.invoke("workbench:import-batch-media", projectId, kind),
    importPromptBatch: (projectId, scope) => ipcRenderer.invoke("workbench:import-prompt-batch", projectId, scope),
    importShotPrompts: projectId => ipcRenderer.invoke("workbench:import-shot-prompts", projectId),
    importFinalVideo: projectId => ipcRenderer.invoke("workbench:import-final-video", projectId),
    analyzeScript: projectId => ipcRenderer.invoke("workbench:analyze-script", projectId),
    rewriteDialogueScript: (projectId, sourceText) => ipcRenderer.invoke("workbench:rewrite-dialogue-script", projectId, sourceText),
    adaptReferenceScript: (projectId, sourceText, instructions) => ipcRenderer.invoke("workbench:adapt-reference-script", projectId, sourceText, instructions),
    applyScriptAdaptation: (projectId, draftId, acceptWarnings) => ipcRenderer.invoke("workbench:apply-script-adaptation", projectId, draftId, acceptWarnings),
    generateTopics: projectId => ipcRenderer.invoke("workbench:generate-topics", projectId),
    generateCompleteScript: projectId => ipcRenderer.invoke("workbench:generate-complete-script", projectId),
    controlScriptGeneration: (projectId, intent) => ipcRenderer.invoke("workbench:control-script-generation", projectId, intent),
    resumeScriptGeneration: projectId => ipcRenderer.invoke("workbench:resume-script-generation", projectId),
    repairProductionContracts: projectId => ipcRenderer.invoke("workbench:repair-production-contracts", projectId),
    repairCharacterReferences: projectId => ipcRenderer.invoke("workbench:repair-character-references", projectId),
    runIdeaPipeline: projectId => ipcRenderer.invoke("workbench:run-idea-pipeline", projectId),
    generateImage: (projectId, stage, entityId, prompt) => ipcRenderer.invoke("workbench:generate-image", projectId, stage, entityId, prompt),
    previewImagePrompt: (projectId, stage, entityId) => ipcRenderer.invoke("workbench:preview-image-prompt", projectId, stage, entityId),
    previewShotVideoPrompt: (projectId, shotId) => ipcRenderer.invoke("workbench:preview-shot-video-prompt", projectId, shotId),
    previewCharacterVideoPrompt: (projectId, characterId) => ipcRenderer.invoke("workbench:preview-character-video-prompt", projectId, characterId),
    refreshCreatorPrompts: (projectId, options) => ipcRenderer.invoke("workbench:refresh-creator-prompts", projectId, options),
    requestPromptReview: (projectId, options) => ipcRenderer.invoke("workbench:request-prompt-review", projectId, options || {}),
    applyPromptProposal: projectId => ipcRenderer.invoke('workbench:apply-prompt-proposal',projectId),
    confirmPromptReviewItem: (projectId, itemId, prompt) => ipcRenderer.invoke("workbench:confirm-prompt-review-item", projectId, itemId, prompt),
    consumePromptReviewAutoOpenPermit: projectId => ipcRenderer.invoke("workbench:consume-prompt-review-auto-open", projectId),
    confirmAllPromptReview: (projectId, entries) => ipcRenderer.invoke("workbench:confirm-all-prompt-review", projectId, entries || []),
    generateCharacterVideo: (projectId, characterId, prompt) => ipcRenderer.invoke("workbench:generate-character-video", projectId, characterId, prompt),
    extractCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:extract-character-voice", projectId, characterId),
    ensureCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:ensure-character-voice", projectId, characterId),
    listVoiceLibrary: () => ipcRenderer.invoke("workbench:list-voice-library"),
    listReusableAssets: kind => ipcRenderer.invoke("workbench:list-reusable-assets", kind),
    bindReusableAsset: (projectId, entityType, entityId, assetId) => ipcRenderer.invoke("workbench:bind-reusable-asset", projectId, entityType, entityId, assetId),
    importReusableAsset: kind => ipcRenderer.invoke("workbench:import-reusable-asset", kind),
    deleteReusableAsset: assetId => ipcRenderer.invoke("workbench:delete-reusable-asset", assetId),
    updateReusableAssetMetadata: (assetId, metadata) => ipcRenderer.invoke("workbench:update-reusable-asset-metadata", assetId, metadata || {}),
    bindLibraryAsset: (projectId, target, assetId) => ipcRenderer.invoke("workbench:bind-library-asset", projectId, target, assetId),
    depositCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:deposit-character-voice", projectId, characterId),
    bindCharacterVoiceLibrary: (projectId, characterId, voiceId) => ipcRenderer.invoke("workbench:bind-character-voice-library", projectId, characterId, voiceId),
    deleteVoiceLibraryEntry: voiceId => ipcRenderer.invoke("workbench:delete-voice-library-entry", voiceId),
    importVoiceLibrary: () => ipcRenderer.invoke("workbench:import-voice-library"),
    generateShotVideo: (projectId, shotId, mode, options = {}) => ipcRenderer.invoke("workbench:generate-shot-video", projectId, shotId, mode, options),
    previewGenerationDependencies: (projectId, shotIds) => ipcRenderer.invoke("workbench:preview-generation-dependencies", projectId, shotIds || []),
    generateAllAssets: projectId => ipcRenderer.invoke("workbench:generate-all-assets", projectId),
    generateAllStoryboards: projectId => ipcRenderer.invoke("workbench:generate-all-storyboards", projectId),
    generateAllShotVideos: projectId => ipcRenderer.invoke("workbench:generate-all-shot-videos", projectId),
    auditMediaQuality: projectId => ipcRenderer.invoke("workbench:audit-media-quality", projectId),
    repairMediaQuality: projectId => ipcRenderer.invoke("workbench:repair-media-quality", projectId),
    runFullPipeline: projectId => ipcRenderer.invoke("workbench:run-full-pipeline", projectId),
    runPipelineFromStage: (projectId, fromStage) => ipcRenderer.invoke("workbench:run-pipeline-from-stage", projectId, fromStage),
    pausePipeline: (projectId, intent) => ipcRenderer.invoke("workbench:pause-pipeline", projectId, intent),
    listProjectsOverview: () => ipcRenderer.invoke("workbench:list-projects-overview"),
    generateLibraryAsset: (projectId, libraryType, assetId) => ipcRenderer.invoke("workbench:generate-library-asset", projectId, libraryType, assetId),
    importTextFile: kind => ipcRenderer.invoke("workbench:import-text-file", kind),
    confirmCandidate: (projectId, candidateId, discardOthers = true) => ipcRenderer.invoke("workbench:confirm-candidate", projectId, candidateId, discardOthers),
    restoreCandidate: (projectId, candidateId) => ipcRenderer.invoke("workbench:restore-candidate", projectId, candidateId),
    acceptQualityWarnings: (projectId, options = {}) => ipcRenderer.invoke("workbench:accept-quality-warnings", projectId, options),
    discardCandidate: (projectId, candidateId) => ipcRenderer.invoke("workbench:discard-candidate", projectId, candidateId),
    discardFailedRecords: (projectId, scope) => ipcRenderer.invoke("workbench:discard-failed-records", projectId, scope),
    clearAutomationFailures: projectId => ipcRenderer.invoke("workbench:clear-automation-failures", projectId),
    stitch: projectId => ipcRenderer.invoke("workbench:stitch", projectId),
    exportJianyingDraft: (projectId, options = {}) => ipcRenderer.invoke("workbench:export-jianying", projectId, options),
    cancelPostProduction: projectId => ipcRenderer.invoke("workbench:cancel-post-production", projectId)
  },
  // T08/T09 / §6.3: single-item prompt chat whitelist API.
  promptChat: {
    createThread: (projectId, itemId, expectedItemRevision) => ipcRenderer.invoke("prompt-chat:create-thread", projectId, itemId, expectedItemRevision),
    sendTurn: (projectId, threadId, clientTurnId, scope, instruction) => ipcRenderer.invoke("prompt-chat:send-turn", projectId, threadId, clientTurnId, scope, instruction),
    getThread: (projectId, threadId, afterMessageId) => ipcRenderer.invoke("prompt-chat:get-thread", projectId, threadId, afterMessageId),
    applyProposal: (projectId, threadId, proposalId, expectedItemRevision, baseHash) => ipcRenderer.invoke("prompt-chat:apply-proposal", projectId, threadId, proposalId, expectedItemRevision, baseHash),
    discardProposal: (projectId, threadId, proposalId) => ipcRenderer.invoke("prompt-chat:discard-proposal", projectId, threadId, proposalId),
    cancelTurn: (projectId, threadId, turnId) => ipcRenderer.invoke("prompt-chat:cancel-turn", projectId, threadId, turnId)
  }
});
