"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("dramaSlot", {
  defaults: () => ipcRenderer.invoke("app:defaults"),
  health: () => ipcRenderer.invoke("bridge:health"),
  diagnostics: () => ipcRenderer.invoke("bridge:diagnostics"),
  startBridge: () => ipcRenderer.invoke("bridge:start"),
  hideXiangsu: () => ipcRenderer.invoke("bridge:hide"),
  chooseMedia: (type, options = {}) => ipcRenderer.invoke("media:choose", { type, ...options }),
  chooseOutput: () => ipcRenderer.invoke("file:choose-output"),
  submit: payload => ipcRenderer.invoke("video:submit", payload),
  query: taskId => ipcRenderer.invoke("video:query", taskId),
  reveal: targetPath => ipcRenderer.invoke("file:reveal", targetPath),
  workbench: {
    listProjects: () => ipcRenderer.invoke("workbench:list-projects"),
    createProject: (title, options) => ipcRenderer.invoke("workbench:create-project", title, options),
    getProject: projectId => ipcRenderer.invoke("workbench:get-project", projectId),
    patchProject: (projectId, patch) => ipcRenderer.invoke("workbench:patch-project", projectId, patch),
    getSettings: () => ipcRenderer.invoke("workbench:get-settings"),
    saveSettings: settings => ipcRenderer.invoke("workbench:save-settings", settings),
    resetSettings: () => ipcRenderer.invoke("workbench:reset-settings"),
    authStatus: () => ipcRenderer.invoke("workbench:auth-status"),
    syncVideoJobs: () => ipcRenderer.invoke("workbench:sync-video-jobs"),
    accountSwitchStatus: () => ipcRenderer.invoke("workbench:account-switch-status"),
    beginAccountSwitch: projectId => ipcRenderer.invoke("workbench:begin-account-switch", projectId),
    verifyAccountSwitch: () => ipcRenderer.invoke("workbench:verify-account-switch"),
    cancelAccountSwitch: () => ipcRenderer.invoke("workbench:cancel-account-switch"),
    testProvider: (kind, config) => ipcRenderer.invoke("workbench:test-provider", kind, config),
    chooseProduct: projectId => ipcRenderer.invoke("workbench:choose-product", projectId),
    importCandidate: (projectId, entityType, entityId, stage) => ipcRenderer.invoke("workbench:import-candidate", projectId, entityType, entityId, stage),
    analyzeScript: projectId => ipcRenderer.invoke("workbench:analyze-script", projectId),
    generateTopics: projectId => ipcRenderer.invoke("workbench:generate-topics", projectId),
    generateCompleteScript: projectId => ipcRenderer.invoke("workbench:generate-complete-script", projectId),
    controlScriptGeneration: (projectId, intent) => ipcRenderer.invoke("workbench:control-script-generation", projectId, intent),
    resumeScriptGeneration: projectId => ipcRenderer.invoke("workbench:resume-script-generation", projectId),
    runIdeaPipeline: projectId => ipcRenderer.invoke("workbench:run-idea-pipeline", projectId),
    generateImage: (projectId, stage, entityId, prompt) => ipcRenderer.invoke("workbench:generate-image", projectId, stage, entityId, prompt),
    remeshCharacterAsset: (projectId, candidateId) => ipcRenderer.invoke("workbench:remesh-character-asset", projectId, candidateId),
    applyFaceGrid: (projectId, candidateId) => ipcRenderer.invoke("workbench:apply-face-grid", projectId, candidateId),
    generateCharacterVideo: (projectId, characterId, prompt) => ipcRenderer.invoke("workbench:generate-character-video", projectId, characterId, prompt),
    extractCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:extract-character-voice", projectId, characterId),
    generateShotVideo: (projectId, shotId, mode) => ipcRenderer.invoke("workbench:generate-shot-video", projectId, shotId, mode),
    generateAllAssets: projectId => ipcRenderer.invoke("workbench:generate-all-assets", projectId),
    generateAllStoryboards: projectId => ipcRenderer.invoke("workbench:generate-all-storyboards", projectId),
    generateAllShotVideos: projectId => ipcRenderer.invoke("workbench:generate-all-shot-videos", projectId),
    auditMediaQuality: projectId => ipcRenderer.invoke("workbench:audit-media-quality", projectId),
    repairMediaQuality: projectId => ipcRenderer.invoke("workbench:repair-media-quality", projectId),
    runFullPipeline: projectId => ipcRenderer.invoke("workbench:run-full-pipeline", projectId),
    runPipelineFromStage: (projectId, fromStage) => ipcRenderer.invoke("workbench:run-pipeline-from-stage", projectId, fromStage),
    pausePipeline: (projectId, intent) => ipcRenderer.invoke("workbench:pause-pipeline", projectId, intent),
    listProjectsOverview: () => ipcRenderer.invoke("workbench:list-projects-overview"),
    generateLibraryAsset: (projectId, libraryType, assetId) => ipcRenderer.invoke("workbench:generate-library-asset", projectId, libraryType, assetId),
    importTextFile: kind => ipcRenderer.invoke("workbench:import-text-file", kind),
    confirmCandidate: (projectId, candidateId, discardOthers = true) => ipcRenderer.invoke("workbench:confirm-candidate", projectId, candidateId, discardOthers),
    stitch: projectId => ipcRenderer.invoke("workbench:stitch", projectId)
  }
});
