"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("dramaSlot", {
  defaults: () => ipcRenderer.invoke("app:defaults"),
  health: () => ipcRenderer.invoke("bridge:health"),
  diagnostics: () => ipcRenderer.invoke("bridge:diagnostics"),
  startBridge: () => ipcRenderer.invoke("bridge:start"),
  hideXiangsu: () => ipcRenderer.invoke("bridge:hide"),
  chooseMedia: (type, options = {}) => ipcRenderer.invoke("media:choose", { type, ...options }),
  chooseOutput: () => ipcRenderer.invoke("file:choose-output"),
  submit: payload => ipcRenderer.invoke("video:submit", payload),
  query: taskId => ipcRenderer.invoke("video:query", taskId),
  reveal: targetPath => ipcRenderer.invoke("file:reveal", targetPath),
  workbench: {
    listProjects: () => ipcRenderer.invoke("workbench:list-projects"),
    createProject: (title, options) => ipcRenderer.invoke("workbench:create-project", title, options),
    deleteProject: projectId => ipcRenderer.invoke("workbench:delete-project", projectId),
    listDeletedProjects: () => ipcRenderer.invoke("workbench:list-deleted-projects"),
    restoreProject: archiveId => ipcRenderer.invoke("workbench:restore-project", archiveId),
    getProject: projectId => ipcRenderer.invoke("workbench:get-project", projectId),
    patchProject: (projectId, patch) => ipcRenderer.invoke("workbench:patch-project", projectId, patch),
    getSettings: () => ipcRenderer.invoke("workbench:get-settings"),
    saveSettings: settings => ipcRenderer.invoke("workbench:save-settings", settings),
    resetSettings: () => ipcRenderer.invoke("workbench:reset-settings"),
    authStatus: () => ipcRenderer.invoke("workbench:auth-status"),
    licenseStatus: () => ipcRenderer.invoke("license:status"),
    licenseActivate: code => ipcRenderer.invoke("license:activate", code),
    licenseLogout: () => ipcRenderer.invoke("license:logout"),
    syncVideoJobs: () => ipcRenderer.invoke("workbench:sync-video-jobs"),
    accountSwitchStatus: () => ipcRenderer.invoke("workbench:account-switch-status"),
    beginAccountSwitch: projectId => ipcRenderer.invoke("workbench:begin-account-switch", projectId),
    verifyAccountSwitch: () => ipcRenderer.invoke("workbench:verify-account-switch"),
    cancelAccountSwitch: () => ipcRenderer.invoke("workbench:cancel-account-switch"),
    testProvider: (kind, config) => ipcRenderer.invoke("workbench:test-provider", kind, config),
    chooseProduct: projectId => ipcRenderer.invoke("workbench:choose-product", projectId),
    importCandidate: (projectId, entityType, entityId, stage) => ipcRenderer.invoke("workbench:import-candidate", projectId, entityType, entityId, stage),
    importBatchMedia: (projectId, kind) => ipcRenderer.invoke("workbench:import-batch-media", projectId, kind),
    importPromptBatch: (projectId, scope) => ipcRenderer.invoke("workbench:import-prompt-batch", projectId, scope),
    importShotPrompts: projectId => ipcRenderer.invoke("workbench:import-shot-prompts", projectId),
    importFinalVideo: projectId => ipcRenderer.invoke("workbench:import-final-video", projectId),
    analyzeScript: projectId => ipcRenderer.invoke("workbench:analyze-script", projectId),
    generateTopics: projectId => ipcRenderer.invoke("workbench:generate-topics", projectId),
    generateCompleteScript: projectId => ipcRenderer.invoke("workbench:generate-complete-script", projectId),
    controlScriptGeneration: (projectId, intent) => ipcRenderer.invoke("workbench:control-script-generation", projectId, intent),
    resumeScriptGeneration: projectId => ipcRenderer.invoke("workbench:resume-script-generation", projectId),
    runIdeaPipeline: projectId => ipcRenderer.invoke("workbench:run-idea-pipeline", projectId),
    generateImage: (projectId, stage, entityId, prompt) => ipcRenderer.invoke("workbench:generate-image", projectId, stage, entityId, prompt),
    previewImagePrompt: (projectId, stage, entityId) => ipcRenderer.invoke("workbench:preview-image-prompt", projectId, stage, entityId),
    previewShotVideoPrompt: (projectId, shotId) => ipcRenderer.invoke("workbench:preview-shot-video-prompt", projectId, shotId),
    previewCharacterVideoPrompt: (projectId, characterId) => ipcRenderer.invoke("workbench:preview-character-video-prompt", projectId, characterId),
    refreshCreatorPrompts: (projectId, options) => ipcRenderer.invoke("workbench:refresh-creator-prompts", projectId, options),
    remeshCharacterAsset: (projectId, candidateId) => ipcRenderer.invoke("workbench:remesh-character-asset", projectId, candidateId),
    applyFaceGrid: (projectId, candidateId) => ipcRenderer.invoke("workbench:apply-face-grid", projectId, candidateId),
    generateCharacterVideo: (projectId, characterId, prompt) => ipcRenderer.invoke("workbench:generate-character-video", projectId, characterId, prompt),
    extractCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:extract-character-voice", projectId, characterId),
    listVoiceLibrary: () => ipcRenderer.invoke("workbench:list-voice-library"),
    listReusableAssets: kind => ipcRenderer.invoke("workbench:list-reusable-assets", kind),
    bindReusableAsset: (projectId, entityType, entityId, assetId) => ipcRenderer.invoke("workbench:bind-reusable-asset", projectId, entityType, entityId, assetId),
    importReusableAsset: kind => ipcRenderer.invoke("workbench:import-reusable-asset", kind),
    deleteReusableAsset: assetId => ipcRenderer.invoke("workbench:delete-reusable-asset", assetId),
    bindLibraryAsset: (projectId, target, assetId) => ipcRenderer.invoke("workbench:bind-library-asset", projectId, target, assetId),
    depositCharacterVoice: (projectId, characterId) => ipcRenderer.invoke("workbench:deposit-character-voice", projectId, characterId),
    bindCharacterVoiceLibrary: (projectId, characterId, voiceId) => ipcRenderer.invoke("workbench:bind-character-voice-library", projectId, characterId, voiceId),
    deleteVoiceLibraryEntry: voiceId => ipcRenderer.invoke("workbench:delete-voice-library-entry", voiceId),
    importVoiceLibrary: () => ipcRenderer.invoke("workbench:import-voice-library"),
    generateShotVideo: (projectId, shotId, mode) => ipcRenderer.invoke("workbench:generate-shot-video", projectId, shotId, mode),
    generateAllAssets: projectId => ipcRenderer.invoke("workbench:generate-all-assets", projectId),
    generateAllStoryboards: projectId => ipcRenderer.invoke("workbench:generate-all-storyboards", projectId),
    generateAllShotVideos: projectId => ipcRenderer.invoke("workbench:generate-all-shot-videos", projectId),
    auditMediaQuality: projectId => ipcRenderer.invoke("workbench:audit-media-quality", projectId),
    repairMediaQuality: projectId => ipcRenderer.invoke("workbench:repair-media-quality", projectId),
    runFullPipeline: projectId => ipcRenderer.invoke("workbench:run-full-pipeline", projectId),
    runPipelineFromStage: (projectId, fromStage) => ipcRenderer.invoke("workbench:run-pipeline-from-stage", projectId, fromStage),
    pausePipeline: (projectId, intent) => ipcRenderer.invoke("workbench:pause-pipeline", projectId, intent),
    listProjectsOverview: () => ipcRenderer.invoke("workbench:list-projects-overview"),
    generateLibraryAsset: (projectId, libraryType, assetId) => ipcRenderer.invoke("workbench:generate-library-asset", projectId, libraryType, assetId),
    importTextFile: kind => ipcRenderer.invoke("workbench:import-text-file", kind),
    confirmCandidate: (projectId, candidateId, discardOthers = true) => ipcRenderer.invoke("workbench:confirm-candidate", projectId, candidateId, discardOthers),
    discardCandidate: (projectId, candidateId) => ipcRenderer.invoke("workbench:discard-candidate", projectId, candidateId),
    discardFailedRecords: (projectId, scope) => ipcRenderer.invoke("workbench:discard-failed-records", projectId, scope),
    clearAutomationFailures: projectId => ipcRenderer.invoke("workbench:clear-automation-failures", projectId),
    stitch: projectId => ipcRenderer.invoke("workbench:stitch", projectId)
  }
});
